### ISSUE TITLE
Not worl $generator->gridMaxColumns

### ISSUE THREAD

**Issue by jumper423** [schmunk42/yii2-giiant#100]
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: schmunk42\giiant\crud\Generator::gridMaxColumns'

Not work if (++$count < $generator->gridMaxColumns)

**Comment by schmunk42** [comment]
- Which giiant version are you using?
- Did you use the web or CLI gii-generator?
- If CLI which, could you paste your command...

**Comment by schmunk42** [comment]
Closed due to inactivity, please reopen if needed.
