### ISSUE TITLE
Calling unknown method: yii\console\Application::getSession()

### ISSUE THREAD

**Issue by jumper423** [schmunk42/yii2-giiant#115]
yii giiant-batch --interactive=0 --overwrite=1 --enableI18N=0 --messageCategory=app --modelNamespace=common\models\tables --crudControllerNamespace=backend\controllers --crudSearchModelNamespace=common\models\tables\search --crudViewPath=@backend/views --crudPathPrefix= --tables=group

Running full giiant batch...
Running 'Giiant Model'...

The following files will be generated:
  [unchanged] E:\OpenServer\domains\marketvk\common\models\tables\base\Group.php

No files were chosen to be generated.
Running 'Giiant CRUD'...

Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\console\Application::getSession()'

in E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\Component.php:285

Stack trace:
#0 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-authclient\BaseOAuth.php(441): yii\base\Component->__call('getSession', Array)
#1 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-authclient\BaseOAuth.php(441): yii\console\Application->getSession()
#2 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-authclient\BaseOAuth.php(410): yii\authclient\BaseOAuth->getState('token')
#3 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-authclient\BaseOAuth.php(128): yii\authclient\BaseOAuth->restoreAccessToken()
#4 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-authclient\BaseOAuth.php(485): yii\authclient\BaseOAuth->getAccessToken()
#5 E:\OpenServer\domains\marketvk\common\models\tables\Group.php(28): yii\authclient\BaseOAuth->api('groups.get', 'GET', Array)
#6 [internal function]: common\models\tables\Group->getGroupSocials()
#7 E:\OpenServer\domains\marketvk\vendor\schmunk42\yii2-giiant\crud\Generator.php(254): call_user_func(Array)
#8 E:\OpenServer\domains\marketvk\vendor\schmunk42\yii2-giiant\crud\Generator.php(209): schmunk42\giiant\crud\Generator->getModelRelations('common\\models\\t...')
#9 E:\OpenServer\domains\marketvk\vendor\schmunk42\yii2-giiant\crud\providers\RelationProvider.php(33): schmunk42\giiant\crud\Generator->getRelationByColumn('common\\models\\t...', Object(yii\db\ColumnSchema))
#10 [internal function]: schmunk42\giiant\crud\providers\RelationProvider->activeField(Object(yii\db\ColumnSchema), Object(common\models\tables\Group))
#11 E:\OpenServer\domains\marketvk\vendor\schmunk42\yii2-giiant\crud\Generator.php(474): call_user_func_array(Array, Array)
#12 E:\OpenServer\domains\marketvk\vendor\schmunk42\yii2-giiant\crud\Generator.php(308): schmunk42\giiant\crud\Generator->callProviderQueue('activeField', Object(yii\db\ColumnSchema), Object(common\models\tables\Group))
#13 E:\OpenServer\domains\marketvk\vendor\schmunk42\yii2-giiant\crud\default\views\_form.php(68): schmunk42\giiant\crud\Generator->activeField(Object(yii\db\ColumnSchema), Object(common\models\tables\Group))
#14 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\View.php(325): require('E:\\OpenServer\\d...')
#15 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('E:\\OpenServer\\d...', Array)
#16 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-gii\Generator.php(317): yii\base\View->renderFile('E:\\OpenServer\\d...', Array, Object(schmunk42\giiant\crud\Generator))
#17 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-gii\generators\crud\Generator.php(173): yii\gii\Generator->render('views/_form.php')
#18 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-gii\console\GenerateAction.php(52): yii\gii\generators\crud\Generator->generate()
#19 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2-gii\console\GenerateAction.php(35): yii\gii\console\GenerateAction->generateCode()
#20 [internal function]: yii\gii\console\GenerateAction->run()
#21 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#22 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Action->runWithParams(Array)
#23 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction('giiant-crud', Array)
#24 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction('giiant-crud', Array)
#25 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\console\Application.php(167): yii\base\Module->runAction('gii/giiant-crud', Array)
#26 E:\OpenServer\domains\marketvk\vendor\schmunk42\yii2-giiant\commands\BatchController.php(239): yii\console\Application->runAction('gii/giiant-crud', Array)
#27 E:\OpenServer\domains\marketvk\vendor\schmunk42\yii2-giiant\commands\BatchController.php(169): schmunk42\giiant\commands\BatchController->actionCruds()
#28 [internal function]: schmunk42\giiant\commands\BatchController->actionIndex()
#29 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#30 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#31 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction('', Array)
#32 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction('', Array)
#33 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\console\Application.php(167): yii\base\Module->runAction('giiant-batch', Array)
#34 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('giiant-batch', Array)
#35 E:\OpenServer\domains\marketvk\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#36 E:\OpenServer\domains\marketvk\yii(31): yii\base\Application->run()
#37 {main}

**Comment by schmunk42** [comment]
Which Yii version do you have?

**Comment by jumper423** [comment]
2.0.6

**Comment by schmunk42** [comment]
Sorry, just noticed that this is not related to the Yii version, but rather to `yii2-authclient`.
In your app there are calls to yii2-authclient\BaseOAuth, which happen for every request, even console commands.

You need to disable auth components and modules for the CLI. They don't have an effect there anyway.
Or more correctly: you need to disabled any component, which is called and which uses a PHP-session.

**Comment by schmunk42** [comment]
for reference: https://github.com/schmunk42/yii2-giiant/blob/master/docs/60-troubleshooting.md#calling-unknown-method-yiiconsoleapplicationgetsession
