### ISSUE TITLE
Relation name generation problems when one table has 2 FK columns pointing to same parent table

### ISSUE THREAD

**Issue by vipantonio** [schmunk42/yii2-giiant#118]
Having two FK columns (in same table), pointing to the same parent table, results in wrong relation method name generation. Model method name for relation is getKlientais0() while view.php file references that model invoking function $model->getKlientais0**s**() (notice last letter "s").

Lets assume we have table Clients (in my language KLIENTAI) and Tags (TAGAI). Clients have 2 FK columns "TAGID" and "TAGID2". Generating model for table "Tags" results in 2 ActiveQuery "hasMany" methods:

```php
public function getKlientais()
{
    return $this->hasMany(\app\models\Klientai::className(), ['tagid' => 'id']);
}
public function getKlientais0()
{
    return $this->hasMany(\app\models\Klientai::className(), ['tagid2' => 'id']);
}
```

whereas views\tagai\view.php file generates this code:
````php
'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getKlientais0s(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-klientais0s']]),
````

I tried this example on Firebird database but this is the same in MySQL. I guess you should use same function for generating RelationNames in model.php and in crud generator view.php.

````sql
CREATE TABLE TAGAI (
    ID    INTEGER NOT NULL,
    NAME  VARCHAR(15) CHARACTER SET ISO8859_13 COLLATE LT_LT
);
ALTER TABLE TAGAI ADD CONSTRAINT PK_TAGAI PRIMARY KEY (ID);

CREATE TABLE KLIENTAI (
    KLIENTOID             INTEGER NOT NULL,
    PAVADINIMAS           VARCHAR(20) CHARACTER SET ISO8859_13,
    TAGID                 INTEGER,
    TAGID2                INTEGER
);
ALTER TABLE KLIENTAI ADD CONSTRAINT PK_KLIENTAI PRIMARY KEY (KLIENTOID);
ALTER TABLE KLIENTAI ADD CONSTRAINT FK_KLIENTAI_2 FOREIGN KEY (TAGID) REFERENCES TAGAI (ID);
ALTER TABLE KLIENTAI ADD CONSTRAINT FK_KLIENTAI_3 FOREIGN KEY (TAGID2) REFERENCES TAGAI (ID);
````
![relation-name-problem](https://cloud.githubusercontent.com/assets/510088/10537244/200115f2-73f9-11e5-9fe0-78e84911a68c.png)

**Comment by schmunk42** [comment]
Thanks for reporting.
We'll look into this.

CC: @Quexer69 @deacix
