### ISSUE TITLE
Generate Relations is invalid

### ISSUE THREAD

**Issue by sum1190** [schmunk42/yii2-giiant#120]
Hi,

I'm using giiant for a personal project based on Yii2 advanced app. I've correctly configured my database and installed giiant. I've created a migration, done it through the CLI "yii" and I would create a model with giiant but this appears:
![schermata-1](https://cloud.githubusercontent.com/assets/5607196/10756153/7e62622a-7ca2-11e5-944a-41160d6e9429.png)

I've filled all the fields and trying various configuration but it doesn't allow any preview. 

Thanks,
Davide.

**Comment by schmunk42** [comment]
Just as a workaround: Can you generate the models on the CLI?

**Comment by sum1190** [comment]
It seems that with the CLI-way, I can generate model..

**Comment by HenryDewa** [comment]
I have the same problem , what's the solution ?

**Comment by sum1190** [comment]
With
https://github.com/trntv/yii2-starter-kit
https://github.com/phundament/app

it works, but with the base and advanced template not. Maybe it's a initialization problem or something similiar..

**Comment by schmunk42** [comment]
Could you check if this https://github.com/schmunk42/yii2-giiant/pull/125 fixes the issue?

**Comment by sum1190** [comment]
I can try these changes in a few days 'cause right now I'm working on a project with Phundament. You'll receive feedback as soon as possible. :)

**Comment by kchechlinski** [comment]
I had this same issue. And it looks that fixes from  #125 works fine.

**Comment by schmunk42** [comment]
Thanks for the feedback, I'll close this one. Please reopen or create a new one, if necessary.
