### ISSUE TITLE
Exception 'ReflectionException' with message 'Class schmunk42\giiant\crud\providers\optsProvider does not exist'

### ISSUE THREAD

**Issue by brucebnu** [schmunk42/yii2-giiant#121]
No files were chosen to be generated.
Running 'Giiant CRUD'...

Exception 'ReflectionException' with message 'Class schmunk42\giiant\crud\providers\optsProvider does not exist'

in /data/www/web/starter/vendor/yiisoft/yii2/di/Container.php:415

command is as follows
./yii giiant-batch \
    --interactive=0 \
    --overwrite=1 \
    --modelDb=db \
    --modelBaseClass=yii\\db\\ActiveRecord \
    --modelNamespace=migrations\\models \
    --crudControllerNamespace=app\\modules\\crud\\controllers \
    --crudSearchModelNamespace=app\\modules\\crud\\models\\search \
    --crudViewPath=@app/modules/crud/views \
    --crudPathPrefix= \
    --crudSkipRelations=Variant,Variants \
    --crudProviders=schmunk42\\giiant\\crud\\providers\\optsProvider \
    --tables=xwg_school

 "schmunk42/yii2-giiant": "*"

**Comment by schmunk42** [comment]
The location of the providers did change recently: `schmunk42\giiant\generators\crud\providers`

**Comment by brucebnu** [comment]
cool, Thank you for everything.

**Comment by jnanendraveer** [comment]
Thanks!
