### ISSUE TITLE
Undefined Constants

### ISSUE THREAD

**Issue by LarryTX** [schmunk42/yii2-giiant#129]
It looks like you may have committed new code yesterday. I'm getting a new error and wondering if the two might be connected. Specifically, the error is: Undefined class constant 'RELATIONS_NONE'. The source of the error is: in <root>\_protected\vendor\schmunk42\yii2-giiant\src\generators\model\form.php and occurs in these lines
```
echo $form->field($generator, 'generateRelations')->dropDownList([    
    \yii\gii\generators\model\Generator::RELATIONS_NONE => Yii::t('yii', 'No relations'),
    \yii\gii\generators\model\Generator::RELATIONS_ALL => Yii::t('yii', 'All relations'),
    \yii\gii\generators\model\Generator::RELATIONS_ALL_INVERSE => Yii::t('yii', 'All relations with inverse'),
]);
```
If it's not a problem with the code, do you have any idea what I could be doing wrong? I can't find any place where the three constants are defined.

**Comment by schmunk42** [comment]
Looks like this is related to b5a8dd2.

@sebathi Any idea about this?

PS: Sorry, I am relying mainly on contributions for the Web UI.

**Comment by PMan2** [comment]
Same issue for me. Yesterday I installed Yii2 basic template via composer, then installed yii2-giant via composer, all without any error. Then i started my project in browser, ran gii and when I chose Giiant Model generator, same Exception occured.

**Comment by schmunk42** [comment]
I will check this, use 0.5.0 in the meantime.

**Comment by LarryTX** [comment]
0.5.0 works perfectly. Good luck on getting the constants definition fixed.
