### ISSUE TITLE
T_NS_SEPARATOR

### ISSUE THREAD

**Issue by abolivar** [schmunk42/yii2-giiant#131]
Clear install app advanced, version 0.7 and dev, i try with 0.6 and ok

![screenshot from 2016-01-20 08-07-44](https://cloud.githubusercontent.com/assets/92059/12449681/f0ebb232-bf4c-11e5-8471-45191d20c1b5.png)

**Comment by schmunk42** [comment]
Did you generate the code via Web UI /gii or console command?

**Comment by abolivar** [comment]
gii

**Comment by abolivar** [comment]
Any idea?

**Comment by schmunk42** [comment]
Would this one https://github.com/schmunk42/yii2-giiant/pull/132 fix it for you?
Sorry, I did not find time yet to look into it.

**Comment by kikoucalou** [comment]
I confirm what appears to be a bug from Web UI /gii as I am a total neophyte, I corrected this error model manualy.
Hats off for this Giiant application.

**Comment by schmunk42** [comment]
Thank you! 

And sorry guys that I don't have more time to fix this at the moment.
I was working on a bunch of tests for the Web UI, but they aren't finished yet.

Just as a general notice: I strongly recommend the [CLI batch command](https://github.com/schmunk42/yii2-giiant/blob/master/src/commands/BatchController.php).

CC: @dmstr/developers
