### ISSUE TITLE
Trying to get property of non-object $pivotName = Inflector::pluralize...

### ISSUE THREAD

**Issue by cloudswitch** [schmunk42/yii2-giiant#135]
Hi, why is that happening? Have I done something worng...? Thanks!

Line 150 in view.php 

$pivotName = Inflector::pluralize($generator->getModelByTableName($relation->via->from[0]));

**Comment by schmunk42** [comment]
Could you post the relevant part of your schema?

**Comment by cloudswitch** [comment]
Schema? How do you mean? As a picture?

**Comment by schmunk42** [comment]
Better would be a SQL dump, but a picture may also help.
Looks like something can not be detected automatically in the schema.

**Comment by cloudswitch** [comment]
I don't know, I'm not sure if I'm allowed to publish it... :/ other way I can help?

**Comment by schmunk42** [comment]
Do you get the error for one or all many-many tables?
Could you verify that `$relation->via` fails (eg. by breaking the lines)?

You could change the names in the schema and show only a part which fails - with changed names.

**Comment by cloudswitch** [comment]
I've found something: I've defined a hasMany()->via() relation. If I comment it out, then it seems to work.

**Comment by schmunk42** [comment]
Did you manually create the models?

**Comment by cloudswitch** [comment]
no, only this extra relation.

**Comment by schmunk42** [comment]
Customizing relations can be tricky, we had a similar problem recently.
If you do that, make sure they are created like Yii 2 does it internally or use `--crudSkipRelations`.

But I think this issue can be closed, right?

**Comment by cloudswitch** [comment]
I think I've done it the Yii2 way... but alright. Thanks a lot!

**Comment by schmunk42** [comment]
You're welcome!

**Comment by schmunk42** [comment]
> I think I've done it the Yii2 way... but alright. Thanks a lot!

Addon: Double-check settings of the customized relation, eg. `$relation->link` or `$relation->via`.

**Comment by cloudswitch** [comment]
If I'm doing it with `viaTable()` instead of `via()`, it seems to work. Can you please help me a little bit how can I check settings of relation? Where do I have to put this code? Sry I'm a beginner, but I want to learn. Thanks!

**Comment by schmunk42** [comment]
It's hard to explain, I was mostly debugging objects returned by relations and tried back-and-forth.

But it would be great if you could create some code to reproduce your issues.

**Comment by lowap** [comment]
public function getCipLands() {
        return $this->hasMany(\app\models\CipLand::className(), ['cip_id' => 'id']);
    }

    public function getLand() {
        return $this->hasMany(\app\models\Land::className(), ['id' => 'land_id'])
                        ->via('cipLands');
    }

If I'm doing so, I'm getting the error.
I've checked $relation->via(), output is okay.

**Comment by lowap** [comment]
Hi,

as I see, **from** is always empty, regardless if the relation was generated by Giiant, or by me, or is it inside of the realtion or in the pivot table. I would really love to understand what is happening there, because I would love to enjoy the benefits of the crud generator bei `via()`, too.

`print_r($relation->via)`:

> [via] => Array
                (
                    [0] => hmWzs
                    [1] => app\models\HmWzQuery Object
                        (
                            [sql] => 
                            [on] => 
                            [joinWith] => 
                            [select] => 
                            [selectOption] => 
                            [distinct] => 
                            [from] => 
                            [groupBy] =>

**Comment by schmunk42** [comment]
@lowap Please open a new issue with an example schema, I do not understand your problem atm.
