### ISSUE TITLE
Can dmstr\helpers\Html be replaced with yii\helpers\Html?

### ISSUE THREAD

**Issue by thadudexx** [schmunk42/yii2-giiant#141]
As it provides less functionality? Are there any drawbacks if we replace dmstr\helpers\Html with yii\helpers\Html to get Html::img functionality?

**Comment by schmunk42** [comment]
Yeah, I saw that also. I'll keep an eye on it.

Basically this Html-helper should do access checks, but there are also issues with this.

**Comment by thadudexx** [comment]
Is the issue that it is to restrictive? Because it doesn´t differ between, framework routes and external url´s?
