### ISSUE TITLE
Add generate ActiveQuery to model generation

### ISSUE THREAD

**Issue by sebathi** [schmunk42/yii2-giiant#146]
A must 👍

**Comment by schmunk42** [comment]
Like this?
- https://github.com/schmunk42/yii2-giiant/blob/master/src/generators/model/default/model.php#L212
- https://github.com/schmunk42/yii2-giiant/blob/master/src/generators/model/default/query.php

**Comment by sebathi** [comment]
Yes, but on the form you don't have the generateActiveQueries Like the one on gii form 👍

**Comment by sebathi** [comment]
https://github.com/yiisoft/yii2-gii/blob/master/generators/model/form.php#L21
