### ISSUE TITLE
SavedForms only load from Modules

### ISSUE THREAD

**Issue by iBotPeaches** [schmunk42/yii2-giiant#155]
Per this commit - https://github.com/schmunk42/yii2-giiant/commit/8bd8f45cf195b64b3211b5e608048ffb5ccf6799 it only loads `.json` files from modules. If you are just using the Yii2 basic project and generating SavedForms for your own models they show up in `@app/gii` which isn't a module thus not loaded into Saved Form dropdown.

**Comment by schmunk42** [comment]
@uldisn Any thoughts about this?

**Comment by uldisn** [comment]
Fixed: In pull request #156 is included @app/gii directory.

**Comment by schmunk42** [comment]
> @app/gii which isn't a module thus not loaded into Saved Form dropdown.

In fact, your app is also a module - an `Application` extends from `Module` - it like the default module.

But anyway - thanks for the report and fix 👍
