### ISSUE TITLE
yii/db/exception SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by khandaa** [schmunk42/yii2-giiant#163]
I am trying to use the tool but everytime it throws this error. I checked on the net and it says that the application is unable to connect to the database. I am able to connect it if I use normal gii.  
I am unable to get past this issue.. please help

**./yii gii/giiant-test --tableName client_configuration --modelClass ClientConfiguration**
Running 'Giiant Test'...

Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'

in /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Connection.php:550

Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Connection.php(864): yii\db\Connection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Connection.php(851): yii\db\Connection->getMasterPdo()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Command.php(894): yii\db\Command->prepare(true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/mysql/Schema.php(198): yii\db\Command->queryAll()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/mysql/Schema.php(97): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Schema.php(149): yii\db\mysql\Schema->loadTableSchema('1')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Connection.php(737): yii\db\Schema->getTableSchema('1', true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2-gii/generators/model/Generator.php(741): yii\db\Connection->getTableSchema('1', true)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/schmunk42/yii2-giiant/src/generators/model/Generator.php(562): yii\gii\generators\model\Generator->getTableNames()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2-gii/generators/model/Generator.php(697): schmunk42\giiant\generators\model\Generator->getTableNames()
#12 [internal function]: yii\gii\generators\model\Generator->validateTableName('tableName', NULL)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/validators/InlineValidator.php(69): call_user_func(Array, 'tableName', NULL)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/validators/Validator.php(252): yii\validators\InlineValidator->validateAttribute(Object(schmunk42\giiant\generators\test\Generator), 'tableName')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Model.php(356): yii\validators\Validator->validateAttributes(Object(schmunk42\giiant\generators\test\Generator), Array)
#16 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2-gii/console/GenerateAction.php(35): yii\base\Model->validate()
#17 [internal function]: yii\gii\console\GenerateAction->run('client_configur...', 'ClientConfigura...')
#18 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)
#19 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('giiant-test', Array)
#21 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('giiant-test', Array)
#22 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('gii/giiant-test', Array)
#23 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('gii/giiant-test', Array)
#24 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#25 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/yii(21): yii\base\Application->run()
#26 {main}

**Comment by schmunk42** [comment]
Can you run another command, beside `gii/giiant-test` like `gii/giiant-model` or `gii/giiant-crud`?

**Comment by khandaa** [comment]
All of them are giving the same error including batch.

**Comment by schmunk42** [comment]
Do you have a custom database connection, like something different than `db`?

**Comment by khandaa** [comment]
This is the only database in my server.. copying my db.php for reference

'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=localhost;dbname=resto_crm',
    //'dsn' => 'mysql:host=localhost;dbname=yii2basic',
    'username' => 'root',

as i understand, console.php would also use the same db.php file and so db access should be no different.

**Comment by khandaa** [comment]
Same error with giiant-model

**./yii gii/giiant-model --tableName client_configuration --modelClass ClientConfiguration**
Running 'Giiant Model'...

Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'

in /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Connection.php:550

Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Connection.php(864): yii\db\Connection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Connection.php(851): yii\db\Connection->getMasterPdo()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Command.php(894): yii\db\Command->prepare(true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/mysql/Schema.php(198): yii\db\Command->queryAll()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/mysql/Schema.php(97): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Schema.php(149): yii\db\mysql\Schema->loadTableSchema('1')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/db/Connection.php(737): yii\db\Schema->getTableSchema('1', true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2-gii/generators/model/Generator.php(741): yii\db\Connection->getTableSchema('1', true)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/schmunk42/yii2-giiant/src/generators/model/Generator.php(562): yii\gii\generators\model\Generator->getTableNames()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2-gii/generators/model/Generator.php(697): schmunk42\giiant\generators\model\Generator->getTableNames()
#12 [internal function]: yii\gii\generators\model\Generator->validateTableName('tableName', NULL)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/validators/InlineValidator.php(69): call_user_func(Array, 'tableName', NULL)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/validators/Validator.php(252): yii\validators\InlineValidator->validateAttribute(Object(schmunk42\giiant\generators\model\Generator), 'tableName')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Model.php(356): yii\validators\Validator->validateAttributes(Object(schmunk42\giiant\generators\model\Generator), Array)
#16 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2-gii/console/GenerateAction.php(35): yii\base\Model->validate()
#17 [internal function]: yii\gii\console\GenerateAction->run('client_configur...', 'ClientConfigura...')
#18 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)
#19 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('giiant-model', Array)
#21 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('giiant-model', Array)
#22 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('gii/giiant-mode...', Array)
#23 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('gii/giiant-mode...', Array)
#24 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#25 /Applications/XAMPP/xamppfiles/htdocs/yii2resto/yii(21): yii\base\Application->run()
#26 {main}

**Comment by schmunk42** [comment]
In your dumps it reads:

```
 yii\db\Connection->getTableSchema('1', true)
```

Looks like the table name is wrong here, should be a name like "client_configuration".
Could you try quoting that?

Are you running this on Windows CMD.exe or Linux?

**Comment by khandaa** [comment]
Tried it with double quotes for both table name as well model name. No luck :(

I am using a macbook.

**Comment by khandaa** [comment]
Code at - vendor/yiisoft/yii2/db/Connection.php:550
checked $this->dsn It is populated with expected values.

$token = 'Opening DB connection: ' . $this->dsn;
        try {
            Yii::info($token, __METHOD__);
            Yii::beginProfile($token, __METHOD__);
            $this->pdo = $this->createPdoInstance();
            $this->initConnection();
            Yii::endProfile($token, __METHOD__);
        } catch (\PDOException $e) {
            Yii::endProfile($token, __METHOD__);
            throw new Exception($e->getMessage(), $e->errorInfo, (int) $e->getCode(), $e);
        }

**Comment by schmunk42** [comment]
Could you try debugging around [here](https://github.com/schmunk42/yii2-giiant/blob/220b614f81ff69dc9d7e9faae6b2d6a846c11ab0/src/generators/model/Generator.php#L242)?

Or could you share the schema?

You can create code blocks with ``` btw

**Comment by khandaa** [comment]
--
-- Table structure for table `client_configuration`
--

CREATE TABLE `client_configuration` (
  `configuration_id` bigint(20) NOT NULL,
  `client_id` bigint(20) NOT NULL,
  `configuration_type` varchar(30) NOT NULL,
  `configuration_variable` varchar(50) NOT NULL,
  `configuration_value` varchar(100) NOT NULL,
  `configuration_status` varchar(10) NOT NULL,
  `conf_start_datetime` datetime DEFAULT NULL,
  `conf_end_datetime` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `client_configuration`
--
ALTER TABLE `client_configuration`
  ADD PRIMARY KEY (`configuration_id`),
  ADD KEY `client_id` (`client_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `client_configuration`
--
ALTER TABLE `client_configuration`
  MODIFY `configuration_id` bigint(20) NOT NULL AUTO_INCREMENT;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `client_configuration`
--
ALTER TABLE `client_configuration`
  ADD CONSTRAINT `cc_fk_1` FOREIGN KEY (`client_id`) REFERENCES `master_client` (`client_id`);

**Comment by khandaa** [comment]
Ah! found the solution here  http://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

I changed the host from "localhost" to "127.0.0.1" and it started working. Thanks for all your help.

**Comment by abuammar** [comment]
change the host from "localhost" to "127.0.0.1"  and php yii migrate

**Comment by abuammar** [comment]
go to 
common/config/main-local.php

and port no

<?php
return [
    'components' => [
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:33060;dbname=abc',
            'username' => 'homestead',
            'password' => 'secret',
            'charset' => 'utf8',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
    ],
];

**Comment by azdanov** [comment]
I've encountered the same problem. Since I was using Homestead for development, this solution might help those who use vagrant.

You need to run the migration command from [inside the virtual machine](https://laravel.com/docs/5.6/homestead#connecting-via-ssh), or as @abuammar said, in development append a port that [Homestead](https://laravel.com/docs/5.6/homestead#connecting-to-databases) uses for communication with the host machine.
