### ISSUE TITLE
BUG: base/*Controller not including `use` for ActiveDataProvider...

### ISSUE THREAD

**Issue by davidjeddy** [schmunk42/yii2-giiant#165]
...when creating a GiiCRUD class collection the base controller is missing the use statement for ActiveDataProvider.

Is
```
<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers\base;

use common\models\ModelName;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
```

Expect
```
<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers\base;

use yii\data\ActiveDataProvider;
use common\models\ModelName;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
```

As per the warning this would not be sustainable as it will be overwriten on next generation.

**Comment by schmunk42** [comment]
You don't need an ActiveDataProvider by default in the Controller. If you'd like to add custom code to your controllers, edit the "empty" Controller class, not the base/Controller. That's how it's supposed to work.

Feel free to comment or reopen, if I had a misunderstanding here.

**Comment by davidjeddy** [comment]
That may be true, however if the option is checkbox=true for activeform then the controller should include ActiveDataProvider. Generated scaffolding logic should work without manual editing.
