### ISSUE TITLE
Use Json file

### ISSUE THREAD

**Issue by alekseyseo** [schmunk42/yii2-giiant#167]
Giiant creates a json file with the settings generated model.
How can I do generate this model with settings from file use console?

**Comment by uldisn** [comment]
Currently this json file can not use in console. I created it for GUI as alternative for editing command line and I use only GUI. Now no see any reason, why need console.

**Comment by alekseyseo** [comment]
I do file for run in console:

`$dir = '......yii2\\';

$regen_models = [
    'yii2_linkGiiantModel.json',
    'yii2_lesson_noteGiiantModel.json',
    'yii2_lessonGiiantModel.json',
    'yii2_teacher_typeGiiantModel.json',
];

$regen_crud = [
    'LinkGiiantCRUD.json',
    'LessonGiiantCRUD.json',
    'LessonNoteGiiantCRUD.json',
    'TeacherTypeGiiantCRUD.json',
];

function get_str($file)
{
    $string = file_get_contents( $file );
    $json_a = json_decode( $string, true );
    $str = '';
    foreach ($json_a as $key => $items) {
        $str .= ' --' . $items['name'] . '=' . $items['value'];
    }
    return $str;
}

if ($argv[1]=='model') {
    foreach ($regen_models as $items){
        passthru($dir . 'yii gii/giiant-model' .get_str($items) );
    }
} elseif ($argv[1]=='crud'){
    foreach ($regen_crud as $items){
        passthru($dir . 'yii gii/giiant-crud' .get_str($items) );
    }
}`

**Comment by uldisn** [comment]
For getting all json files You can use https://github.com/schmunk42/yii2-giiant/blob/master/src/helpers/SaveForm.php#L35
