### ISSUE TITLE
Model name is not applying to generated file name

### ISSUE THREAD

**Issue by StalkAlex** [schmunk42/yii2-giiant#176]
Hi guys, I am using web giiant to generate model for a newly created table. But name from model class field is not applied to the final generated file, it uses table name instead.
![1](https://cloud.githubusercontent.com/assets/2943154/18942453/9b2d0546-8632-11e6-9742-c81322e4200f.PNG)
![2](https://cloud.githubusercontent.com/assets/2943154/18942455/9f11a2ca-8632-11e6-98a6-6988acde6a2d.PNG)

**Comment by tonymrakovcic** [comment]
Yes, this would be a life saver

**Comment by jewbre** [comment]
this needs to be added, it's getting on my nerve already :@

**Comment by krukru** [comment]
Any news on this request?

**Comment by schmunk42** [comment]
PRs highly welcome! 

To be honest, we never use the Web UI, only CLI. I wanted to remove that a while ago - **but** it seems a lot of people are using it.

**Comment by schmunk42** [comment]
fixed in #184
