### ISSUE TITLE
Documentation is not compatible with Yii2 advanced application

### ISSUE THREAD

**Issue by saidbakr** [schmunk42/yii2-giiant#191]
> It's recommended to configure a customized batch command in your application CLI configuration.

I could not find the file in which those configuration should be placed!

**Comment by schmunk42** [comment]
Should be in your application config, I've updated the docs.

**Comment by schmunk42** [comment]
Actually the default configuration should be compatible with the advanced app.
I am not using it, but I kept it like that for BC.

Which errors do you get when running the batch command without params?

**Comment by saidbakr** [comment]
Actually many errors, including missing category of `models` for localization. Additionally, the dependency seems to have issues because there are some extensions missing.

However, I tried it with basic app and it works more easier.

**Comment by schmunk42** [comment]
> Actually many errors, including missing category of models for localization.

Same like https://github.com/schmunk42/yii2-giiant/issues/190 ?

> Additionally, the dependency seems to have issues because there are some extensions missing.

Which ones?
