### ISSUE TITLE
ReflectionException Class yii\web\grid\ActionColumn does not exist

### ISSUE THREAD

**Issue by bryan1996akl** [schmunk42/yii2-giiant#192]
After generating all my models and crud I get this error for every model's view index.php "ReflectionException Class yii\web\grid\ActionColumn does not exist". Anything obvious for me to check?
`

    1. in /var/www/html/uofapp2/vendor/yiisoft/yii2/di/Container.php at line 424

         * @return array the dependencies of the specified class.
         */
        protected function getDependencies($class)
        {
            if (isset($this->_reflections[$class])) {
                return [$this->_reflections[$class], $this->_dependencies[$class]];
            }
     
            $dependencies = [];
            $reflection = new ReflectionClass($class);
     
            $constructor = $reflection->getConstructor();
            if ($constructor !== null) {
                foreach ($constructor->getParameters() as $param) {
                    if ($param->isDefaultValueAvailable()) {
                        $dependencies[] = $param->getDefaultValue();
                    } else {
                        $c = $param->getClass();
                        $dependencies[] = Instance::of($c === null ? null : $c->getName());

    2. in /var/www/html/uofapp2/vendor/yiisoft/yii2/di/Container.php at line 424 – ReflectionClass::__construct('yii\web\grid\ActionColumn')
    3. in /var/www/html/uofapp2/vendor/yiisoft/yii2/di/Container.php at line 364 – yii\di\Container::getDependencies('yii\web\grid\ActionColumn')
    4. in /var/www/html/uofapp2/vendor/yiisoft/yii2/di/Container.php at line 156 – yii\di\Container::build('yii\web\grid\ActionColumn', [], ['grid' => yii\grid\GridView, 'template' => '<div class="action-buttons">{vie...', 'buttons' => ['view' => Closure], 'urlCreator' => Closure, ...])
    5. in /var/www/html/uofapp2/vendor/yiisoft/yii2/BaseYii.php at line 344 – yii\di\Container::get('yii\web\grid\ActionColumn', [], ['grid' => yii\grid\GridView, 'template' => '<div class="action-buttons">{vie...', 'buttons' => ['view' => Closure], 'urlCreator' => Closure, ...])
    6. in /var/www/html/uofapp2/vendor/yiisoft/yii2/grid/GridView.php at line 533 – yii\BaseYii::createObject(['grid' => yii\grid\GridView, 'template' => '<div class="action-buttons">{vie...', 'buttons' => ['view' => Closure], 'urlCreator' => Closure, ...])
    7. in /var/www/html/uofapp2/vendor/yiisoft/yii2/grid/GridView.php at line 278 – yii\grid\GridView::initColumns()
    8. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/Object.php at line 107 – yii\grid\GridView::init()
    9. yii\base\Object::__construct(['dataProvider' => yii\data\ActiveDataProvider, 'pager' => ['class' => 'yii\widgets\LinkPager', 'firstPageLabel' => 'First', 'lastPageLabel' => 'Last'], 'filterModel' => backend\models\SchoolSearch, 'tableOptions' => ['class' => 'table table-striped table-border...'], ...])
    10. in /var/www/html/uofapp2/vendor/yiisoft/yii2/di/Container.php at line 381 – ReflectionClass::newInstanceArgs([['dataProvider' => yii\data\ActiveDataProvider, 'pager' => ['class' => 'yii\widgets\LinkPager', 'firstPageLabel' => 'First', 'lastPageLabel' => 'Last'], 'filterModel' => backend\models\SchoolSearch, 'tableOptions' => ['class' => 'table table-striped table-border...'], ...]])
    11. in /var/www/html/uofapp2/vendor/yiisoft/yii2/di/Container.php at line 156 – yii\di\Container::build('yii\grid\GridView', [], ['dataProvider' => yii\data\ActiveDataProvider, 'pager' => ['class' => 'yii\widgets\LinkPager', 'firstPageLabel' => 'First', 'lastPageLabel' => 'Last'], 'filterModel' => backend\models\SchoolSearch, 'tableOptions' => ['class' => 'table table-striped table-border...'], ...])
    12. in /var/www/html/uofapp2/vendor/yiisoft/yii2/BaseYii.php at line 344 – yii\di\Container::get('yii\grid\GridView', [], ['dataProvider' => yii\data\ActiveDataProvider, 'pager' => ['class' => 'yii\widgets\LinkPager', 'firstPageLabel' => 'First', 'lastPageLabel' => 'Last'], 'filterModel' => backend\models\SchoolSearch, 'tableOptions' => ['class' => 'table table-striped table-border...'], ...])
    13. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/Widget.php at line 136 – yii\BaseYii::createObject(['dataProvider' => yii\data\ActiveDataProvider, 'pager' => ['class' => 'yii\widgets\LinkPager', 'firstPageLabel' => 'First', 'lastPageLabel' => 'Last'], 'filterModel' => backend\models\SchoolSearch, 'tableOptions' => ['class' => 'table table-striped table-border...'], ...])
    14. in /var/www/html/uofapp2/backend/views/school/index.php at line 309 – yii\base\Widget::widget(['dataProvider' => yii\data\ActiveDataProvider, 'pager' => ['class' => 'yii\widgets\LinkPager', 'firstPageLabel' => 'First', 'lastPageLabel' => 'Last'], 'filterModel' => backend\models\SchoolSearch, 'tableOptions' => ['class' => 'table table-striped table-border...'], ...])

                            return '';
                        }
                    },
                    'format' => 'raw',
                ],
                'nssfemployeerate',
                'nssfemployerrate',
                /*'notes:ntext',*/
                /*'date_entered',*/
                /*'date_updated',*/
                /*'email:email',*/
                /*'phone1',*/
                /*'phone2',*/

    15. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/View.php at line 328 – require('/var/www/html/uofapp2/backend/vi...')
    16. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/View.php at line 250 – yii\base\View::renderPhpFile('/var/www/html/uofapp2/backend/vi...', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => backend\models\SchoolSearch])
    17. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/View.php at line 152 – yii\base\View::renderFile('/var/www/html/uofapp2/backend/vi...', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => backend\models\SchoolSearch], backend\controllers\SchoolController)
    18. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/Controller.php at line 381 – yii\base\View::render('index', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => backend\models\SchoolSearch], backend\controllers\SchoolController)
    19. in /var/www/html/uofapp2/backend/controllers/base/SchoolController.php at line 45 – yii\base\Controller::render('index', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => backend\models\SchoolSearch])

     
    Url::remember();
    \Yii::$app->session['__crudReturnUrl'] = null;
     
    return $this->render('index', [
    'dataProvider' => $dataProvider,
        'searchModel' => $searchModel,
    ]);
    }
     
    /**
    * Displays a single School model.
    * @param integer $id

    20. backend\controllers\base\SchoolController::actionIndex()
    21. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([backend\controllers\SchoolController, 'actionIndex'], [])
    22. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams(['r' => 'school'])
    23. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/Module.php at line 523 – yii\base\Controller::runAction('', ['r' => 'school'])
    24. in /var/www/html/uofapp2/vendor/yiisoft/yii2/web/Application.php at line 102 – yii\base\Module::runAction('school', ['r' => 'school'])
    25. in /var/www/html/uofapp2/vendor/yiisoft/yii2/base/Application.php at line 380 – yii\web\Application::handleRequest(yii\web\Request)
    26. in /var/www/html/uofapp2/backend/web/index.php at line 17 – yii\base\Application::run()
    11121314151617

        require(__DIR__ . '/../../common/config/main.php'),
        require(__DIR__ . '/../../common/config/main-local.php'),
        require(__DIR__ . '/../config/main.php'),
        require(__DIR__ . '/../config/main-local.php')
    );
     
    (new yii\web\Application($config))->run();

$_GET = [
    'r' => 'school',
];

$_COOKIE = [
    'advanced-backend' => 'u697ucfqqj9tbrhpa6oapirrn3',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/uofapp2/backend/web/index.php?r=school',
    '__crudReturnUrl' => null,
];

Yii Framework

2017-02-16, 17:23:43

Apache/2.4.18 (Ubuntu)

Yii Framework/2.0.11.2
`

**Comment by schmunk42** [comment]
This should already be fixed in https://github.com/schmunk42/yii2-giiant/commit/683373c22f466c49ddcd2b3c3c2d9899a3235899

Would you mind trying this branch https://github.com/schmunk42/yii2-giiant/tree/feature/no-sql - it's just called no-sql, because of additional support, it should also work with relational DBs - tests are also passing.

**Comment by bryan1996akl** [comment]
Yes, this problem is fixed in [683373c](https://github.com/schmunk42/yii2-giiant/commit/683373c22f466c49ddcd2b3c3c2d9899a3235899) as you suggested. Thanks!
