### ISSUE TITLE
Can't find a way to disable generating controllers and views with CLI

### ISSUE THREAD

**Issue by Suseika** [schmunk42/yii2-giiant#198]
I am using the command line to generate models with giiant:

```bash
yii batch
```

What do I put into the application configuration or command line options to disable generating views and controllers?

I tried looking at the source of BatchController to see if there are options for that, but I can't find any.

http://stackoverflow.com/questions/43238066/how-to-disable-generating-controllers-and-views-with-cli-for-giiant

**Comment by schmunk42** [comment]
I've updated the docs: https://github.com/schmunk42/yii2-giiant/blob/master/docs/25-cli-commands.md#batch-command

    yii giiant-batch/models

Should do the job, when using the batch. Or you can use the gii generator `gii/giiant-model`.
