### ISSUE TITLE
Getting unknown property: schmunk42\giiant\generators\model\Generator::generateQuery

### ISSUE THREAD

**Issue by mavs1971** [schmunk42/yii2-giiant#209]
i install yii2-giiant, first i gat Undefined class constant 'RELATIONS_NONE', i delete 5 line and i add line that you mention it on https://github.com/schmunk42/yii2-giiant/issues/129, but then when i made the sugestion i get this error Getting unknown property: schmunk42\giiant\generators\model\Generator::generateQuery on line echo $form->field($generator, 'generateQuery')->checkbox();

i install the  0.5.0 in the meantime., but get the same mistake

**Comment by schmunk42** [comment]
Should be fixed in newer versions, please let me know if not.
