### ISSUE TITLE
ReflectionException method does not exist

### ISSUE THREAD

**Issue by lowap** [schmunk42/yii2-giiant#218]
Hi,

**I love giiant**! Together with this, I have always trouble with generating CRUD code, because of `Inflector::pluralize` (I think, but I'm not sure) (maybe it's because of Gii).

I've now found that 
> if you need relation via multiple tables you have to use via() instead of viaTable(). viaTable() is for convenience to specify a many to many relation more easily.

I have a few relations with multiple tables.

For example, I have a single, standalone `hasOne` relation `getFzzdb()`. If I'm using multiple `viaTable`s in other relations (these have nothing to do with `getFzzdb()`), I'm getting a `ReflectionException ... Method app\models\Zwz::getFzzdbs() does not exist` error _(please note the "s" at the end)_. I have tried with **Singular Entities** on and off - no difference (what difference does it make anyway?). 

If I'm doing it with `via()` how it now seems should be, then I'm getting:
> PHP Notice – yii\base\ErrorException
Trying to get property of non-object
in C:\...\vendor\schmunk42\yii2-giiant\src\generators\crud\default\views\view.php
> 141. $pivotName = Inflector::pluralize($generator->getModelByTableName($relation->via->from[0]));

If I'm doing so in:
`...\vendor\schmunk42\yii2-giiant\src\generators\crud\default\views\view.php`

`//$pivotName = Inflector::pluralize($generator->getModelByTableName($relation->via->from[0]));`
`$pivotName = $generator->getModelByTableName($relation->via->from[0]);`

then it's working for relation `getFzzdb()`, but not for other hasMany relations (I would have to delete all "s"-s at the end of all other hasMany relations). So I think giiant basically doesn't work together with `via()`...? Only with `viaTable()`? What am I doing wrong? How should I define my relations in order to make it work?

I know you are very busy, but I'm relying on giiant so much, can you please check this for me? Or to make it work through `via()`?

Thanks in advance!

**Comment by schmunk42** [comment]
Sorry for the very late response.

Basically giiant works with all relation types provided by Yii's DAO.
An important thing for MANY-MANY relations is that your junction table MUST have a composite primary key and no auto-increment one.

The differences between singular and plural are used to distinguish relations which return just one one or many records.

Closing this, let me know if there are open points.
