### ISSUE TITLE
"Object" is not valid class name in PHP 7.2, batch is failing

### ISSUE THREAD

**Issue by Nex-Otaku** [schmunk42/yii2-giiant#224]
Trying to run 
`yii batch`

gives error:

> PHP Compile Error 'yii\base\ErrorException' with message 'Cannot use yii\base\Object as Object because 'Object' is a special class name'
> 
> \vendor\schmunk42\yii2-giiant\src\base\Provider.php:10

PHP 7.2 does not allow "Object" as class name. Please fix.

**Comment by schmunk42** [comment]
Could you try with `0.10.0-beta2` and report if it works.

**Comment by schmunk42** [comment]
Should be fixed since version mentioned above.
