### ISSUE TITLE
Unable to locate message source for category 'cruds'.

### ISSUE THREAD

**Issue by akiraz2** [schmunk42/yii2-giiant#229]
I generate crud from web
Then I go to backend (mycontroller/index) and got error:

> Invalid Configuration – yii\base\InvalidConfigException
> Unable to locate message source for category 'cruds'.

\index.php at line 104
![image](https://user-images.githubusercontent.com/24400393/39192867-d986a108-47e2-11e8-93dc-45151012266d.png)
![image](https://user-images.githubusercontent.com/24400393/39192884-e7b3a190-47e2-11e8-91e0-3e41a0da2915.png)

**Comment by schmunk42** [comment]
Elements in generated CRUDs are meant to be translated with this category `cruds`.
Can you describe your issue a bit more?

**Comment by akiraz2** [comment]
I propose to add the translation of all non-configurable categories in your repository

**Comment by schmunk42** [comment]
But you can configure the translation catalogue (category), or?

**Comment by eluhr** [comment]
This is fixed in the latest version (1.0.0)
