### ISSUE TITLE
Unable to locate message source for category 'giiant'.

### ISSUE THREAD

**Issue by sohel8537** [schmunk42/yii2-giiant#234]
please help me 

Invalid Configuration – yii\base\InvalidConfigException

 **Unable to locate message source for category 'giiant'.**

**Comment by schmunk42** [comment]
Can you describe the actions you do, before the error occurs.

**Comment by liasica** [comment]
@sohel8537 
In your components add
```json
'i18n'         => [
            'translations' => [
                '*' => [
                    'class'          => 'yii\i18n\PhpMessageSource',
                    'basePath'       => '@app/messages', // if advanced application, set @frontend/messages
                    'sourceLanguage' => 'en',
                    'fileMap'        => [
                        //'main' => 'main.php',
                    ],
                ],
            ],
        ],
```

It works for me

**Comment by KrishnaPB** [comment]
Hi, @sohel8537 ,

Where (in which file) exactly need add the above code to fix the issue?

**Comment by cebe** [comment]
@KrishnaPB this needs to be configuted in application config under `components` section. The above code configures the `i18n` component.

**Comment by KrishnaPB** [comment]
thank you very much
