### ISSUE TITLE
Possibility of XSS Attack

### ISSUE THREAD

**Issue by maximilianoraul** [schmunk42/yii2-giiant#236]
In the generation of CRUD Forms Html :: encode is not used to sanitize the outputs of the variables, if the ID that is used is not numeric an attacker could inject code through the loading of malicious code.
Example: src/generators/crud/default/views/view.php line 66
`<?= '<?= $model->'.$generator->getModelNameAttribute($generator->modelClass)." ?>\n" ?>`
Should be
`<?= '<?= Html::encode($model->'.$generator->getModelNameAttribute($generator->modelClass).") ?>\n" ?>`
and in
create.php line 37
update.php line 40

https://www.yiiframework.com/doc/guide/2.0/en/security-best-practices#avoiding-xss

**Comment by maximilianoraul** [comment]
https://github.com/schmunk42/yii2-giiant/pull/237

**Comment by schmunk42** [comment]
Merged #237 - thank you!
