### ISSUE TITLE
How to create AccessFilter?

### ISSUE THREAD

**Issue by thadudexx** [schmunk42/yii2-giiant#256]
as $generateAccessFilterMigration is hardcoded to false?

**Comment by schmunk42** [comment]
Since it's a generator property you can set it via CLI, see https://github.com/schmunk42/yii2-giiant/blob/master/src/generators/crud/Generator.php#L97

**Comment by thadudexx** [comment]
after i added the property to the batchcontroller, or i am missing something?

**Comment by schmunk42** [comment]
That was added here: https://github.com/schmunk42/yii2-giiant/commit/1614d4e41f90876c8e40ecabc5c6d40657726711

Which version are you using?

**Comment by thadudexx** [comment]
sorry my fault overlooked that commit. I am using latest stable, 0.10.8, thats why its missing.

**Comment by schmunk42** [comment]
So, you just need to upgrade to `0.11.0-beta2`

**Comment by thadudexx** [comment]
yea thanks, would you recommend to upgrade to the beta version yet?

**Comment by schmunk42** [comment]
There *should* be no issues. We've also updated the CHANGELOG (https://github.com/schmunk42/yii2-giiant/blob/master/CHANGELOG.md) - so please give it a try and give feedback.

**Comment by thadudexx** [comment]
Thank you for the info. I will give it a try.
