### ISSUE TITLE
$aliasModel in model template

### ISSUE THREAD

**Issue by mj4444ru** [schmunk42/yii2-giiant#266]
https://github.com/schmunk42/yii2-giiant/blob/3d00e9c03d7d19a0366cca09d2825c099b1ec589/src/generators/model/default/model.php#L50

Property $aliasModel was previously removed. Why is it present in the template?

**Comment by schmunk42** [comment]
Looks like a left-over or bug. 

I didn't find the commit where it was removed, do you have corresponding commit-SHA?

**Comment by mj4444ru** [comment]
https://github.com/schmunk42/yii2-giiant/blob/master/CHANGELOG.md#080
https://github.com/schmunk42/yii2-giiant/commit/d1ffd3b76a2ab6cac473839e640ed6d2c1becbdf
https://github.com/schmunk42/yii2-giiant/commit/21bfc2fb0612ed0710296c93c54ac33e6e25bca8

**Comment by schmunk42** [comment]
Can you create a PR?

**Comment by eluhr** [comment]
This is fixed in version 1.0.0
