### ISSUE TITLE
updated gii JSON form config path creates two bugs

### ISSUE THREAD

**Issue by OndrejVasicek** [schmunk42/yii2-giiant#277]
Hi Schmunk42.
This commit https://github.com/schmunk42/yii2-giiant/commit/52a14ac3027b6898debf565a378fcb378ed3ac31 breaks two things in situation you want to load already saved form.

1) The “JSON_PRETT_PRINT” makes the JS code corrupted and it breaks any JS functionality, like filling the fields.
![image](https://user-images.githubusercontent.com/3864012/103302079-10ac0b80-4a03-11eb-9b91-bac7c3df955f.png)
![image](https://user-images.githubusercontent.com/3864012/103302096-19044680-4a03-11eb-9d43-28015eb9721a.png)
![image](https://user-images.githubusercontent.com/3864012/103302117-25889f00-4a03-11eb-99ab-f12fa2e628a8.png)

2) The loadSavedForms() in SaveForm.php can’t find the new path because the folder "gii" is hardcoded there.
![image](https://user-images.githubusercontent.com/3864012/103302240-75fffc80-4a03-11eb-9f11-61df1d90336e.png)
If I change it to:
![image](https://user-images.githubusercontent.com/3864012/103302259-87e19f80-4a03-11eb-87f7-d4121ec2fd2d.png)
it works but of course the bug 1) still persists.

**Comment by schmunk42** [comment]
Folder was moved recently, could your create a PR?

**Comment by OndrejVasicek** [comment]
I could do a PR for that small change, but it's very bad solution. I don't think the path should be hardcoded at various places.
It should be set in some config or constant. 
You have some variables `$giiInfoPath` in crud\Generator.php and model\Generator.php, but I don't know if this is it and how it is accessible from the static method loadSavedForms().
I really think it needs some proper design, which I'm not capable of, cause I don't know the plugin.
Maybe with some help I could help.

Also it doesn't solve the first problem with the JS. When you started using the new JSON formatting, there was probably a reason for that. I can't just switch that back, can I?

**Comment by uldisn** [comment]
Why can't I use the current module directory gii?

**Comment by schmunk42** [comment]
I just moved the info files to a folder named `.gii` (from `gii`) since it was cluttering the "standard" source code directories. I.e. we ignore `.gii` because we do not use the web UI at all.

**Comment by uldisn** [comment]
Created PR: https://github.com/schmunk42/yii2-giiant/pull/278

**Comment by schmunk42** [comment]
merged and available in 0.13.0-beta2
