### ISSUE TITLE
method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [schmunk42/yii2-giiant#288]
On PHP 8.1.5, when we access Giiant Model on browser, 

![image](https://user-images.githubusercontent.com/6583254/204749601-78481047-0695-4ff2-86e0-81c4c78fbebf.png)

**Comment by schmunk42** [comment]
CC: @handcode @eluhr

**Comment by handcode** [comment]
have never used this (and probably never will), but this should  be "fixed" in #286
