### ISSUE TITLE
Model generator doesn't use the Model Class field

### ISSUE THREAD

**Issue by pafnow** [schmunk42/yii2-giiant#29]
Hi again,

I notice that when I'm using the Giiant Model generator, the Model Class field seems not to be used to define the class name and the file name.
In my case, I name the table Countries in my database but would like to get the model generated called Country. I fill the generator form with
Table Name = Counties
Model Name = Country
But the generator keeps creating CountriesBase and Countries files and classes.

I looked into the code and I fix the issue by addiing:
    if (isset($this->classNames[$tableName])) {
        return $this->classNames[$tableName];
    }
at the beginning of  the function
        protected function generateClassName($tableName)
in the file yii2-giiant/model/Generator.php

Actually I get this piece of code from the yii2-gii generator and I notice that you renamed classNames to classNames2. I didin't dare to touch what you did so I just add my three lines of code.

Any better solution?

**Comment by tsvetann** [comment]
@schmunk42 I also used $this->classNames directly and had no issues at all! But if you are having conflicts in any edge cases then we can at least assign $this->classNames2 = $this->classNames and continue with $this->classNames2 and would still work. Defining table name mappings is not a nice solution. What do you think?

**Comment by santilin** [comment]
I have a related problem. When my table name is all upper case, the model class name is also uppercase. For example, if I set 

tablename: CATEGORY
Modelname: Category

giiant generates files like CATEGORYBase.php and CATEGORY.php and if I generate the CRUD, the views folder is named c-a-t-e-g-o-r-y.

I have fixed it by lowercasing the classname in src/generators/model/Generator.php, in function generateClassName, in the call to id2camel():

        $returnName = Inflector::id2camel(strtolower($className), '_');

and now it works well.

**Comment by schmunk42** [comment]
@santilin Could you create a PR?

**Comment by santilin** [comment]
Sure, but..., what is a PR? :)

**Comment by schmunk42** [comment]
@santilin See here ... https://help.github.com/articles/using-pull-requests/

**Comment by santilin** [comment]
Done!
