### ISSUE TITLE
Provide the Yii::t function within Labels and Links

### ISSUE THREAD

**Issue by marneu** [schmunk42/yii2-giiant#31]
just an idea...

**Comment by Quexer69** [comment]
good idea :) 

**Updates**

* add the missing public property enable I18N to BatchController
* add the missing checkbox for I18N in giiant CRUD webinterface
* use $generator->generateString() in crud templates for I18N support

The updates are already implemented. I will test it the next days and provide them in the next release.

**Comment by Quexer69** [comment]
fixes in commit b0bb2592c3

**Comment by Quexer69** [comment]
@marneu check out dev-master. full i18n support implemented.
