### ISSUE TITLE
CRUD error

### ISSUE THREAD

**Issue by progmax** [schmunk42/yii2-giiant#37]
When you try to log in Giiant CRUD generator:

PHP User Error – yii\base\ErrorException

Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: schmunk42\giiant\crud\Generator::moduleID' 

in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Component.php:143

Stack trace:
#0 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/helpers/BaseHtml.php(1838): yii\base\Component->__get('moduleID')
#1 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/helpers/BaseHtml.php(1139): yii\helpers\BaseHtml::getAttributeValue(Object(schmunk42\giiant\crud\Generator), 'moduleID')
#2 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/helpers/BaseHtml.php(1160): yii\helpers\BaseHtml::activeInput('text', Object(schmunk42\giiant\crud\Generator), 'moduleID', Array)
#3 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/widgets/ActiveField.php(177): yii\helpers\BaseHtml::activeTextInput(Object(schmunk42\giiant\crud\Generator), 'moduleID', Array)
#4 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/widgets/ActiveField.php(149): yii\widgets\ActiveField->render()
#5 /var/www/avtopoch.apronim.io/www/advanced/vendor/schmunk42/yii2-giiant/crud/form.php(12): yii\widgets\ActiveField->__toString()
#6 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/avtopo...')
#7 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/avtopo...', Array)
#8 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2-gii/views/default/view.php(38): yii\base\View->renderFile('/var/www/avtopo...', Array)
#9 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/avtopo...')
#10 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/avtopo...', Array)
#11 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/avtopo...', Array, Object(yii\gii\controllers\DefaultController))
#12 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Controller.php(367): yii\base\View->render('view', Array, Object(yii\gii\controllers\DefaultController))
#13 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2-gii/controllers/DefaultController.php(56): yii\base\Controller->render('view', Array)
#14 [internal function]: yii\gii\controllers\DefaultController->actionView('giiant-crud')
#15 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#16 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('view', Array)
#18 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction('gii/default/vie...', Array)
#19 /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /var/www/avtopoch.apronim.io/www/advanced/backend/web/index.php(18): yii\base\Application->run()
#21 {main}
1. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/ErrorHandler.php at line 233
   224225226227228229230231232233234235236237238239240241242    /**
   - Converts an exception into a PHP error.
     *
   - This method can be used to convert exceptions inside of methods like `__toString()`
   - to PHP errors because exceptions cannot be thrown inside of them.
   - @param \Exception $exception the exception to convert to a PHP error.
     */
     public static function convertExceptionToError($exception)
     {
     trigger_error(static::convertExceptionToString($exception), E_USER_ERROR);
     }
   
   /**
   - Converts an exception into a simple string.
   - @param \Exception $exception the exception being converted
   - @return string the string representation of the exception.
     */
     public static function convertExceptionToString($exception)
     {
2. yii\base\ErrorHandler::handleError(256, 'Exception (Unknown Property) 'yi...', '/var/www/avtopoch.apronim.io/www...', 233, ...)
3. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/ErrorHandler.php – trigger_error('Exception (Unknown Property) 'yi...', 256) at line 233
4. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/widgets/ActiveField.php – yii\base\ErrorHandler::convertExceptionToError(yii\base\UnknownPropertyException) at line 151
5. in /var/www/avtopoch.apronim.io/www/advanced/vendor/schmunk42/yii2-giiant/crud/form.php – yii\widgets\ActiveField::__toString() at line 12
   6789101112131415161718 */

echo $form->field($generator, 'modelClass');
echo $form->field($generator, 'searchModelClass');
echo $form->field($generator, 'controllerClass');
echo $form->field($generator, 'baseControllerClass');
echo $form->field($generator, 'moduleID');
echo $form->field($generator, 'viewPath');
echo $form->field($generator, 'pathPrefix');
echo $form->field($generator, 'indexWidgetType')->dropDownList(
    [
        'grid' => 'GridView',
        'list' => 'ListView',
6. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php – require('/var/www/avtopoch.apronim.io/www...') at line 325
7. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php – yii\base\View::renderPhpFile('/var/www/avtopoch.apronim.io/www...', ['generator' => schmunk42\giiant\crud\Generator, 'form' => yii\widgets\ActiveForm]) at line 247
8. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2-gii/views/default/view.php – yii\base\View::renderFile('/var/www/avtopoch.apronim.io/www...', ['generator' => schmunk42\giiant\crud\Generator, 'form' => yii\widgets\ActiveForm]) at line 38
32333435363738394041424344    ]); ?>
        <div class="row">
            <div class="col-lg-8 col-md-10">
                <?= $this->renderFile($generator->formView(), [
                    'generator' => $generator,
                    'form' => $form,
                ]) ?>
                <?= $form->field($generator, 'template')->sticky()
                    ->label('Code Template')
                    ->dropDownList($templates)->hint('
                        Please select which set of the templates should be used to generated the code.
                ') ?>
                <div class="form-group">
9. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php – require('/var/www/avtopoch.apronim.io/www...') at line 325
10. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php – yii\base\View::renderPhpFile('/var/www/avtopoch.apronim.io/www...', ['generator' => schmunk42\giiant\crud\Generator, 'id' => 'giiant-crud']) at line 247
11. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/View.php – yii\base\View::renderFile('/var/www/avtopoch.apronim.io/www...', ['generator' => schmunk42\giiant\crud\Generator, 'id' => 'giiant-crud'], yii\gii\controllers\DefaultController) at line 149
12. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Controller.php – yii\base\View::render('view', ['generator' => schmunk42\giiant\crud\Generator, 'id' => 'giiant-crud'], yii\gii\controllers\DefaultController) at line 367
13. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2-gii/controllers/DefaultController.php – yii\base\Controller::render('view', ['generator' => schmunk42\giiant\crud\Generator, 'id' => 'giiant-crud']) at line 56
50515253545556575859606162                    $params['files'] = $files;
                    $params['answers'] = isset($_POST['answers']) ? $_POST['answers'] : null;
                }
            }
        }

```
    return $this->render('view', $params);
}

public function actionPreview($id, $file)
{
    $generator = $this->loadGenerator($id);
    if ($generator->validate()) {
```
1. yii\gii\controllers\DefaultController::actionView('giiant-crud')
2. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/InlineAction.php – call_user_func_array([yii\gii\controllers\DefaultController, 'actionView'], ['giiant-crud']) at line 55
3. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Controller.php – yii\base\InlineAction::runWithParams(['r' => 'gii/default/view', 'id' => 'giiant-crud']) at line 151
4. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Module.php – yii\base\Controller::runAction('view', ['r' => 'gii/default/view', 'id' => 'giiant-crud']) at line 455
5. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/web/Application.php – yii\base\Module::runAction('gii/default/view', ['r' => 'gii/default/view', 'id' => 'giiant-crud']) at line 83
6. in /var/www/avtopoch.apronim.io/www/advanced/vendor/yiisoft/yii2/base/Application.php – yii\web\Application::handleRequest(yii\web\Request) at line 375
7. in /var/www/avtopoch.apronim.io/www/advanced/backend/web/index.php – yii\base\Application::run() at line 18
   12131415161718    require(**DIR** . '/../../common/config/main-local.php'),
   require(**DIR** . '/../config/main.php'),
   require(**DIR** . '/../config/main-local.php')
   );

$application = new yii\web\Application($config);
$application->run();
 $_GET = [
    'r' => 'gii/default/view',
    'id' => 'giiant-crud',
];

$_SERVER = [
    'HTTP_HOST' => 'avtopoch.apronim.io',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36',
    'HTTP_DNT' => '1',
    'HTTP_REFERER' => 'http://avtopoch.apronim.io/advanced/backend/web/index.php?r=gii%2Fdefault%2Fview&id=giiant-model',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch',
    'HTTP_ACCEPT_LANGUAGE' => 'ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4',
    'HTTP_COOKIE' => 'dle_user_id=1; dle_password=70fce4c199805e5b8e703176bd8c0dd4; dle_compl=0; dle_newpm=0; member_id=1; PHPSESSID=f0d3e78l9853vreu91gtgr8qa7; _csrf=7154364cc64ec598bc12b5f78d4fbf44c12a7148f0029ddbd1694011a47f9b52s%3A32%3A%22dC31l-UicmOOYm-HO5lg7Uocmh6v0CSp%22%3B',
    'PATH' => '/usr/local/bin:/usr/bin:/bin',
    'SERVER_SIGNATURE' => '
Apache/2.2.16 (Debian) Server at avtopoch.apronim.io Port 80

',
    'SERVER_SOFTWARE' => 'Apache/2.2.16 (Debian)',
    'SERVER_NAME' => 'avtopoch.apronim.io',
    'SERVER_ADDR' => '195.211.103.208',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '146.185.187.152',
    'DOCUMENT_ROOT' => '/var/www/avtopoch.apronim.io/www',
    'SERVER_ADMIN' => 'webmaster@localhost',
    'SCRIPT_FILENAME' => '/var/www/avtopoch.apronim.io/www/advanced/backend/web/index.php',
    'REMOTE_PORT' => '30744',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => 'r=gii%2Fdefault%2Fview&id=giiant-crud',
    'REQUEST_URI' => '/advanced/backend/web/index.php?r=gii%2Fdefault%2Fview&id=giiant-crud',
    'SCRIPT_NAME' => '/advanced/backend/web/index.php',
    'PHP_SELF' => '/advanced/backend/web/index.php',
    'REQUEST_TIME_FLOAT' => 1418261101.9960001,
    'REQUEST_TIME' => 1418261101,
];

$_COOKIE = [
    'dle_user_id' => '1',
    'dle_password' => '70fce4c199805e5b8e703176bd8c0dd4',
    'dle_compl' => '0',
    'dle_newpm' => '0',
    'member_id' => '1',
    'PHPSESSID' => 'f0d3e78l9853vreu91gtgr8qa7',
    '_csrf' => '7154364cc64ec598bc12b5f78d4fbf44c12a7148f0029ddbd1694011a47f9b52s:32:"dC31l-UicmOOYm-HO5lg7Uocmh6v0CSp";',
];
Yii Framework
2014-12-11, 04:25:02

Apache/2.2.16 (Debian)
Yii Framework/2.0.1

**Comment by schmunk42** [comment]
```
Getting unknown property: schmunk42\giiant\crud\Generator::moduleID
```

Please check if you're running the latest version `0.2.0` or `dev-master` this was due to an Yii 2 API change.
