### ISSUE TITLE
Fail to generate CRUD from many-to-many relationship

### ISSUE THREAD

**Issue by ramoscarlos** [schmunk42/yii2-giiant#45]
I am having an issue when generating CRUD for a many-to-many relationship. I have two models, *Empresa* and *Regimen*, and one table to join them together (for which I have no model since is just a glue table).
When I try to use Giiant CRUD, I get the error:
    **Unknown Method – yii\base\UnknownMethodException**
    **Calling unknown method: backend\models\Regimen::getEmpresaRegimens()**
Which is a method that calls the model *EmpresaRegimen* that doesn't exist. As far as I am concerned with standards, glue tables like that (only *empresa_id* and *regimen_id* being the fields) should not have model file. Or am I wrong in such interpretation?

Anyhow, even if I change the code in the base model from getEmpresaRegimens to the next function,
```
public function getEmpresas(){
    return $this->hasMany(\common\models\Empresa::className(), ['id' => 'empresa_id'])->viaTable('empresa_regimen', ['regimen_id' => 'id']);
}
```
the error of the relationship still appears, asking for the same *getEmpresaRegimens* function. After eliminating the function `getEmpresas()` the generator works, albeit it doesn't build the relationship. My question is, is my relationship code or the lack of glue model wrong? or is a problem of the generator?
Regards.

**Comment by schmunk42** [comment]
> Which is a method that calls the model EmpresaRegimen that doesn't exist. As far as I am concerned with standards, glue tables like that (only empresa_id and regimen_id being the fields) should not have model file. Or am I wrong in such interpretation?

Basically you're right, if you generate your models and CRUDs **manually** you can work around this issue and you do not have to generate models for the glue (pivot) tables.
But on the other hand you have to prepare your controllers to handle the saving of the related records. Yii 2 comes equipped with a `link()` method which does most of the job for you, see also http://stackoverflow.com/a/26781976/291573

In giiant I decided to implement the generation of CRUDs in a very basic and generic way, which includes also the generation of CRUDs for the pivot tables.
The reason behind this decision is, that it is very hard to automate the generation of input and the saving of related data.

So for now, you'd have to generate a model for your pivot tables and then regenerate the CRUDs.

But I'll keep this issue open - it's on the roadmap to improve this.

**Comment by ramoscarlos** [comment]
> In giiant I decided to implement the generation of CRUDs in a very basic and generic way, which includes also the generation of CRUDs for the pivot tables.

I see. Then, I am going to stick to the use of models for the pivot tables.

One question, though. Is the model the only thing neccesary or do I need to create a controller and views associated to the pivot tables?

Regards.

**Comment by schmunk42** [comment]
You need everything, but Giiant should do the whole job for you.
Please make sure you have a composite PK for your pivot table.

Usually I am creating the CRUD in a separate folder or module and don't them afterwards.
All customization is done through providers btw 

Von meinem iPad gesendet

**Comment by schmunk42** [comment]
I'll try to setup a demo application to make things more clear.

**Comment by ramoscarlos** [comment]
Thanks for the info!

> Please make sure you have a composite PK for your pivot table. 

It seems that I lack more knowledge than what I thought at first u.u. I have not declared the composite key so far. In my migration, I have a foreign key relation to both tables, as:
```php
$this->addForeignKey('empresa__regimen__e', 'empresa_regimen', 'empresa_id', 'empresa', 'id', 'RESTRICT', 'CASCADE');
$this->addForeignKey('empresa__regimen__r', 'empresa_regimen', 'regimen_id', 'regimen', 'id', 'RESTRICT', 'CASCADE');
```
Then I would need to declare the primary key as:
```php
$this->addPrimaryKey('empresa_regimen_pk', 'empresa_regimen', 'empresa_id, regimen_id');
```
> You need everything, but Giiant should do the whole job for you.
> All customization is done through providers btw

So, I have to use the code generator (Giiant) to scaffold a lot of the code and then leave the base class alone forever. And all the database interactions I need would be done on the model that inherits from the base class, where I will start to use data providers to, well, provide the records.

So much new information. I think I have to read a Yii2 book before proceeding further.

And the demo would be more than welcome.

**Comment by schmunk42** [comment]
Here's the temporary demo:
http://playground-ee59a477-1.schmunk.cont.tutum.io:49160

Source:
https://github.com/phundament/playground

But I still need to review your latest comment...

**Comment by schmunk42** [comment]
New demo URL see: https://github.com/phundament/playground

Closing issue, please let me know if you've still have questions.
