### ISSUE TITLE
Option for generating test cases

### ISSUE THREAD

**Issue by tsvetann** [schmunk42/yii2-giiant#48]
What about option to generate basic model/controller tests?

**Comment by schmunk42** [comment]
Thanks for your comment!
We also thought about this and it's planned.

**Comment by tsvetann** [comment]
We are using your generator in our project. Is there something we can help here to add tests faster? :)

**Comment by schmunk42** [comment]
What do you think should be tested, i.e.?

Just access to 
- crud/model-name/index
- crud/model-name/create
- existence of relation dropdown(?)

Any more ideas?

- view(?) - how to create data ... with faker?

**Comment by tsvetann** [comment]
as a start we could generate tests for model -> crud operations. may be test actions return code (200). We can start with this and add as we go

**Comment by schmunk42** [comment]
Sounds goods to me, PRs are always welcome.

Another thing is how to run the tests in the current application?
