### ISSUE TITLE
Generating constant holders for attribute names

### ISSUE THREAD

**Issue by tsvetann** [schmunk42/yii2-giiant#49]
What do you think about generating constants one for each attribute name for facilitate faster reference in query strings such as

BaseModel.php:
`const CUSTOMER_USERNAME='username'`
in query where clause later
`$model->where([BaseModel::CUSTOMER_USERNAME => 'admin'])`

The idea is you don't need to remember the AR attr name but as soon as you type BaseModel:: and you get the constants autosuggested for you. It may accelerate coding this way. You don't have to switch between model files to copy the exact attribute name!

**Comment by schmunk42** [comment]
@motin @Quexer69 What do you think?

I am not against it, just would like to evaluate, if there's a slimmer solution.

@tsvetann Is it only about auto-completion?

**Comment by tsvetann** [comment]
Actually, it's about faster insertion of attribute names into query building which comes from the auto-completion and allows not to mistype an attribute name by selecting from autocompletion. Slimmer solution would be even better.

An example:
instead of typing the actual attribute name such as in:
`$model->where(['sales_order_fk' => $orderId])`
You don't have to remember or search for the *sales_order_fk* name but rather
`$model->where(Model::ATTR_SALES_ORDER_FK => $orderId)`
It looks bigger but actually it is faster to insert due to autocompletion and less prone to spelling errors.

**Comment by schmunk42** [comment]
Would there be another prefix than ATTR_?

**Comment by tsvetann** [comment]
We can be fully flexible regarding the prefix name. In my example above I suggested ATTR but it can be smth else. And we should use the same attribute prefix for all constants. (or it can be configurable in the generator template?) The idea is to know what all your attribute constants start with and then you have ATTR_attribute_name_here such as ATTR_USERNAME, ATTR_STATUS...etc. The constants should go in the base model.
