### ISSUE TITLE
Invalid Parameter – yii\base\InvalidParamException in giiant crud generator

### ISSUE THREAD

**Issue by paultipper** [schmunk42/yii2-giiant#51]
I'm trying to generate a CRUD from a model using the giiant CRUD generator, but when I do so, I get the following error:

'yii\base\InvalidParamException' with message 'Invalid path alias: @backend/views' in C:\php\medexpenses\vendor\yiisoft\yii2\BaseYii.php:152

The stack trace is as follows:

#0 C:\php\medexpenses\vendor\schmunk42\yii2-giiant\crud\Generator.php(175): yii\BaseYii::getAlias('@backend/views') #1 C:\php\medexpenses\vendor\yiisoft\yii2-gii\generators\crud\Generator.php(166): schmunk42\giiant\crud\Generator->getViewPath() #2 C:\php\medexpenses\vendor\yiisoft\yii2-gii\controllers\DefaultController.php(45): yii\gii\generators\crud\Generator->generate() #3 [internal function]: yii\gii\controllers\DefaultController->actionView('giiant-crud') #4 C:\php\medexpenses\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array) #5 C:\php\medexpenses\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array) #6 C:\php\medexpenses\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('view', Array) #7 C:\php\medexpenses\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('gii/default/vie...', Array) #8 C:\php\medexpenses\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) #9 C:\php\medexpenses\web\index.php(12): yii\base\Application->run() #10 {main}

I've only just installed giiant this afteroon using Composer, so perhaps I missed a configuration step.

Any ideas?

**Comment by paultipper** [comment]
I've realised that, since I last developed a Yii 2 application about 6 months ago, both the standard and the giiant CRUD generators now ask for a View Path, which I'm sure wasn't the case previously. I think the immediate cause of my problem was that I don't have a @backend alias set up (indeed, I don't even know how to set up aliases at this point).

I then tried entering the relative path to the views directory in the View Path field; I tried both "views" and "app\views", but each time it created my view directory in the web folder, rather than in the project's base folder, which is what I intended.

I was able to work around this by manually moving the views directory up from the web to the base directory, but can someone please tell me what to enter into the "View Path" field so that the CRUD generator generates the views directory in the base directory?

**Comment by kamilplewka** [comment]
in a basic template use @app alias

**Comment by schmunk42** [comment]
You can set up aliases like so https://github.com/phundament/playground/blob/3877996aa19c73fb56f71e520e08ff83228402dc/config/bootstrap.php
