### ISSUE TITLE
Controller generation question

### ISSUE THREAD

**Issue by tsvetann** [schmunk42/yii2-giiant#55]
When a controller is generated the create action is handled in a try/catch statement and all caught exceptions are stored as user input error. Is there any specific reason this is handled that way. I am concerned about the security implications this might have!

Thx

**Comment by schmunk42** [comment]
Sorry for my very late response.

The reason is that, if there's a foreign key constraint error while saving a record, this error is catched an attached as a validation error to the model.

But, while reviewing it, I noticed that this should be improved to catch only database exceptions.

Thanks for reporting.

**Comment by tsvetann** [comment]
Just to inform you that I had a case with broken query and the whole query got displayed in the error message!

**Comment by schmunk42** [comment]
Can you distinguish between a query error and FK error based on the exception type?

**Comment by schmunk42** [comment]
Error messages should be less verbose now (dev-master; major-changes) ...

![bildschirmfoto 2015-06-10 um 21 08 07](https://cloud.githubusercontent.com/assets/649031/8099803/ea258ec2-1002-11e5-9187-d9762b1f9346.png)

@tsvetann What do you think?

**Comment by tsvetann** [comment]
@schmunk42 I still think it can scare non-tech admins :) In a business project I would almost always be requested to change it with something more meaningful.

**Comment by schmunk42** [comment]
Sure ;) My question was about the security issue, because of the full SQL command shown.

**Comment by tsvetann** [comment]
Ah :) then yes much better
