### ISSUE TITLE
Error message on latest update

### ISSUE THREAD

**Issue by LarryTX** [schmunk42/yii2-giiant#56]
Thought you'd like to know. I just updated giiant, and where it was working before, now I get this error message:
```
 PHP Strict Warning – yii\base\ErrorException
Declaration of schmunk42\giiant\model\Generator::generateClassName() should be compatible with yii\gii\generators\model\Generator::generateClassName($tableName, $useSchemaName = NULL)
```

**Comment by schmunk42** [comment]
Hmm, strange - the declaration looks identical to me.
Could you post the output of `composer show -i`?

**Comment by LarryTX** [comment]
Actually, I seem to have resolved the problem by setting up a new Yii2 advanced template project and copying the config files, models, etc. to the new project. But since you asked, here's the composer output:
```
L:\xampp\htdocs\public_html>composer show -i
2amigos/yii2-arrayquery-component   0.1.1              Yii2 component that allows for searching/filtering the elements of an array.
2amigos/yii2-ckeditor-widget        1.0.3              CKEditor widget for Yii2.
2amigos/yii2-multi-select-widget    0.1.1              Multiselect Bootstrap widget for Yii2.
2amigos/yii2-packagist-component    0.1.1              Yii 2 Packagist API extension component.
2amigos/yii2-pjax-filter-behavior   0.1.0              Yii2 filters that filters HTTP requests to ensure pjax calls.
2amigos/yii2-selectize-widget       1.0.1              The selectize.js widget for the Yii framework
2amigos/yii2-taggable-behavior      0.1.0              This extension allows you to get functional for tagging.
bower-asset/admin-lte               v2.0.5             Admin dashboard and control panel template
bower-asset/bootstrap               v3.3.4             The most popular front-end framework for developing responsive, mobile fi...
bower-asset/jquery                  2.1.3
bower-asset/jquery-ui               1.11.4
bower-asset/jquery.inputmask        3.1.62             jquery.inputmask is a jquery plugin which create an input mask.
bower-asset/microplugin             v0.0.3             A lightweight plugin / dependency system for javascript libraries.
bower-asset/moment                  2.10.2
bower-asset/punycode                v1.3.2
bower-asset/selectize               v0.12.0            Selectize is a jQuery-based custom <select> UI control. Useful for taggin...
bower-asset/sifter                  v0.4.1             A library for textually searching arrays and hashes of objects by propert...
bower-asset/typeahead.js            v0.10.5
bower-asset/yii2-pjax               dev-master 3f20897
c006/yii2-migration-utility         dev-master 71c923d Automatically writes the create tables for migrations or create tables in...
cebe/markdown                       1.0.2              A super fast, highly extensible markdown parser for PHP
cebe/yii2-gravatar                  1.1                Gravatar Widget for Yii 2
ckeditor/ckeditor                   4.4.7              JavaScript WYSIWYG web text editor.
creocoder/yii2-nested-sets          0.9.0              The nested sets behavior for the Yii framework
cyneek/yii2-menu                    dev-master f9682a3 DataBase loader with menu items for Kartik Menu Widget.
dektrium/yii2-user                  v0.9.4             Flexible user registration and authentication module for Yii2
dmstr/yii2-adminlte-asset           dev-master dde1111 Backend theme for Yii2 Framework
dmstr/yii2-bootstrap                0.1.1              yii2 bootstrap components and extensions from diemeisterei GmbH
ezyang/htmlpurifier                 v4.6.0             Standards compliant HTML filter written in PHP
facebook/php-sdk-v4                 4.0.23             Facebook SDK for PHP
flexibuild/migrate                  dev-master 9ca9ab8 Helpful tools for yii2 migrations
fortawesome/font-awesome            v4.3.0             The iconic font and CSS framework
fzaninotto/faker                    v1.4.0             Faker is a PHP library that generates fake data for you.
guzzle/guzzle                       v3.8.1             Guzzle is a PHP HTTP client library and framework for building RESTful we...
kartik-v/bootstrap-checkbox-x       v1.5.1             An extended checkbox plugin for bootstrap with three states and additiona...
kartik-v/bootstrap-fileinput        v4.1.8             An enhanced HTML 5 file input for Bootstrap 3.x with features for file pr...
kartik-v/bootstrap-popover-x        v1.4.1             Bootstrap Popover Extended - Popover with modal behavior, styling enhance...
kartik-v/bootstrap-star-rating      v3.5.1             A simple yet powerful JQuery star rating plugin for Bootstrap.
kartik-v/bootstrap-tabs-x           v1.3.0             Extended Bootstrap Tabs with ability to align tabs in multiple ways, add ...
kartik-v/dependent-dropdown         v1.4.0             A multi level dependent dropdown JQuery plugin that allows nested depende...
kartik-v/mpdf                       v1.0.1             A PHP class to generate PDF files from HTML with Unicode/UTF-8 and CJK su...
kartik-v/php-date-formatter         v1.3.0             A JQuery datetime formatting and manipulation library using PHP date-time...
kartik-v/strength-meter             v1.1.1             A dynamic strength meter for password input validation with various confi...
kartik-v/yii2-builder               v1.6.0             Build forms (single-row or multi-row/tabular) easily for Yii Framework 2.0
kartik-v/yii2-checkbox-x            v1.0.0             Extended checkbox widget for bootstrap with three states and additional s...
kartik-v/yii2-date-range            v1.6.1             An advanced Yii 2 date range picker input for based on bootstrap-daterang...
kartik-v/yii2-datecontrol           v1.9.1             Date control module allowing separation of formats for View and Model for...
kartik-v/yii2-detail-view           v1.7.0             Various enhancements to the Yii 2 Detail View with ability to edit data a...
kartik-v/yii2-dropdown-x            v1.2.0             An extended bootstrap dropdown widget for Yii 2 with submenu drilldown.
kartik-v/yii2-editable              v1.7.2             An enhanced editable widget for Yii 2.0 that allows easy editing of displ...
kartik-v/yii2-grid                  v3.0.1             Yii 2 GridView on steroids. Various enhancements and utilities for the Yi...
kartik-v/yii2-helpers               v1.3.0             A collection of useful helper functions for Yii Framework 2.0
kartik-v/yii2-icons                 v1.3.0             Set of icon frameworks for use in Yii Framework 2.0
kartik-v/yii2-krajee-base           v1.7.4             Base library and foundation components for all Yii2 Krajee extensions.
kartik-v/yii2-money                 v1.2.0             An advanced money mask input for Yii 2.0 based on jquery maskmoney plugin...
kartik-v/yii2-mpdf                  v1.0.0             A Yii2 wrapper component for the mPDF library which generates PDF files f...
kartik-v/yii2-nav-x                 v1.2.0             An extended bootstrap Nav widget for Yii 2 with submenu drilldown.
kartik-v/yii2-password              v1.5.0             Useful password strength validation utilities for Yii Framework 2.0
kartik-v/yii2-popover-x             v1.3.0             An extended bootstrap 3.0 popover widget which combines both the bootstra...
kartik-v/yii2-social                v1.3.0             Module containing useful widgets for Yii Framework 2.0 that integrates so...
kartik-v/yii2-sortable              v1.1.0             Create sortable lists and grids using HTML5 drag and drop API for Yii 2.0.
kartik-v/yii2-tabs-x                v1.2.0             An extended bootstrap 3.0 tabs widget with ability to align tabs in multi...
kartik-v/yii2-tree-manager          dev-master 43946bd An enhanced tree management module with tree node selection and manipulat...
kartik-v/yii2-widget-activeform     v1.4.1             Enhanced Yii2 active-form and active-field with full bootstrap styling su...
kartik-v/yii2-widget-affix          v1.0.0             A scrollspy and affixed enhanced navigation to highlight page sections (s...
kartik-v/yii2-widget-alert          v1.1.0             A widget to generate alert based notifications using bootstrap-alert plug...
kartik-v/yii2-widget-colorinput     v1.0.0             An enhanced Yii 2 widget encapsulating the HTML 5 color input (sub repo s...
kartik-v/yii2-widget-datepicker     v1.3.2             Enhanced Yii2 wrapper for the bootstrap datepicker plugin (sub repo split...
kartik-v/yii2-widget-datetimepicker v1.4.0             Enhanced Yii2 wrapper for the bootstrap datetimepicker plugin (sub repo s...
kartik-v/yii2-widget-depdrop        v1.0.0             Widget that enables setting up dependent dropdowns with nested dependenci...
kartik-v/yii2-widget-fileinput      v1.0.1             An enhanced FileInput widget for Bootstrap 3.x with file preview, multipl...
kartik-v/yii2-widget-growl          v1.1.0             A widget to generate growl based notifications using bootstrap-growl plug...
kartik-v/yii2-widget-rangeinput     v1.0.0             An enhanced Yii 2 widget encapsulating the HTML 5 range input (sub repo s...
kartik-v/yii2-widget-rating         v1.0.0             A Yii2 widget for the simple yet powerful bootstrap-star-rating plugin wi...
kartik-v/yii2-widget-select2        v1.0.0             Enhanced Yii2 wrapper for the Select2 jQuery plugin (sub repo split from ...
kartik-v/yii2-widget-sidenav        v1.0.0             An enhanced side navigation menu styled for bootstrap (sub repo split fro...
kartik-v/yii2-widget-spinner        v1.0.0             A widget to render animated CSS3 loading spinners with VML fallback for I...
kartik-v/yii2-widget-switchinput    v1.3.0             A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes &...
kartik-v/yii2-widget-timepicker     v1.0.0             Enhanced Yii2 wrapper for the bootstrap timepicker plugin (sub repo split...
kartik-v/yii2-widget-touchspin      v1.2.0             A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes &...
kartik-v/yii2-widget-typeahead      v1.0.0             Enhanced Yii2 wrapper for the Twitter Typeahead plugin (sub repo split fr...
kartik-v/yii2-widgets               v3.4.0             Collection of useful widgets for Yii Framework 2.0 extending functionalit...
mdmsoft/yii2-admin                  1.0.4              Auth manager for Yii2
mdmsoft/yii2-ar-behaviors           1.0.0              Behaviors for Yii2
mdmsoft/yii2-gii                    1.1.0              Yii2 custom generator for gii
nemmo/yii2-attachments              dev-master e6e24e0 Extension for file uploading and attaching to the models
phpspec/php-diff                    v1.0.2             A comprehensive library for generating differences between two hashable o...
rmrevin/yii2-fontawesome            2.9.1              Asset Bundle for Yii2 with Font Awesome
schmunk42/yii2-giiant               dev-master c7b8b18 Gii CRUD generator for Yii 2 Framework
schmunk42/yii2-packaii              dev-master 97b0368 Yii2 Framework Web-UI for browsing composer packages
swiftmailer/swiftmailer             v5.4.0             Swiftmailer, free feature-rich PHP mailer
symfony/event-dispatcher            v2.6.6             Symfony EventDispatcher Component
warrence/yii2-kartikgii             dev-master 6b0c0e8 Gii Generator base on Kartik-V extension https://github.com/kartik-v
yiisoft/yii2                        2.0.3              Yii PHP Framework Version 2
yiisoft/yii2-authclient             2.0.3              External authentication via OAuth and OpenID for the Yii framework
yiisoft/yii2-bootstrap              2.0.3              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-codeception            2.0.3              The Codeception integration for the Yii framework
yiisoft/yii2-composer               2.0.3              The composer plugin for Yii extension installer
yiisoft/yii2-debug                  2.0.3              The debugger extension for the Yii framework
yiisoft/yii2-faker                  2.0.3              Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                    2.0.3              The Gii extension for the Yii framework
yiisoft/yii2-jui                    2.0.3              The Jquery UI extension for the Yii framework
yiisoft/yii2-swiftmailer            2.0.3              The SwiftMailer integration for the Yii framework
zhuravljov/yii2-datetime-widgets    1.0.1              Datetime widgets for Yii2.

L:\xampp\htdocs\public_html>
```
My guess is that, on one of the composer-update something got into conflict with giiant. (I have had perennial problems with Yii2 updates; each one of them seems to require some adjustments to get stuff back in sync. The joy of a large, complex project.)

**Comment by juan88** [comment]
I'm experiencing the same issue. I think my version of yii is 2.0.4-dev. Might be related to this?

in yii\gii\generators\model\Generator,
`protected function generateClassName($tableName, $useSchemaName = null)` 
function is declared like this. Where as in 2.0.2 version of yii the same function is declared like 
`protected function generateClassName($tableName)`

Hope it helps!

**Comment by philippfrenzel** [comment]
@juan88 you are right, it's because of this change...

**Comment by danielblues** [comment]
I also have this issue running from the console

<pre>
./yii 
PHP Strict Warning 'yii\base\ErrorException' with message 'Declaration of schmunk42\giiant\model\Generator::generateClassName() should be compatible with yii\gii\generators\model\Generator::generateClassName($tableName, $useSchemaName = NULL)'

in /home/alumni/public_html/vendor/schmunk42/yii2-giiant/model/Generator.php:217

Stack trace:
#0 /home/alumni/public_html/vendor/yiisoft/yii2/BaseYii.php(288): yii\base\ErrorHandler->handleError(2048, 'Declaration of ...', '/home/alumni/pu...', 217, Array)
#1 /home/alumni/public_html/vendor/yiisoft/yii2/BaseYii.php(288): yii\BaseYii::autoload()
#2 [internal function]: yii\BaseYii::autoload('schmunk42\\giian...')
#3 [internal function]: spl_autoload_call('schmunk42\\giian...')
#4 /home/alumni/public_html/vendor/yiisoft/yii2/di/Container.php(415): ReflectionClass->__construct('schmunk42\\giian...')
#5 /home/alumni/public_html/vendor/yiisoft/yii2/di/Container.php(358): yii\di\Container->getDependencies('schmunk42\\giian...')
#6 /home/alumni/public_html/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('schmunk42\\giian...', Array, Array)
#7 /home/alumni/public_html/vendor/yiisoft/yii2/BaseYii.php(340): yii\di\Container->get('schmunk42\\giian...', Array)
#8 /home/alumni/public_html/vendor/yiisoft/yii2-gii/console/GenerateController.php(74): yii\BaseYii::createObject('schmunk42\\giian...')
#9 /home/alumni/public_html/vendor/yiisoft/yii2/base/Object.php(107): yii\gii\console\GenerateController->init()
#10 /home/alumni/public_html/vendor/yiisoft/yii2/base/Controller.php(81): yii\base\Object->__construct(Array)
#11 [internal function]: yii\base\Controller->__construct('gii', Object(yii\console\Application), Array)
#12 /home/alumni/public_html/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->newInstanceArgs(Array)
#13 /home/alumni/public_html/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('yii\\gii\\console...', Array, Array)
#14 /home/alumni/public_html/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('yii\\gii\\console...', Array, Array)
#15 /home/alumni/public_html/vendor/yiisoft/yii2/base/Module.php(508): yii\BaseYii::createObject(Array, Array)
#16 /home/alumni/public_html/vendor/yiisoft/yii2/console/controllers/HelpController.php(92): yii\base\Module->createController('gii')
#17 /home/alumni/public_html/vendor/yiisoft/yii2/console/controllers/HelpController.php(184): yii\console\controllers\HelpController->getCommandDescriptions()
#18 /home/alumni/public_html/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#19 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#20 /home/alumni/public_html/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#21 /home/alumni/public_html/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#22 /home/alumni/public_html/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#23 /home/alumni/public_html/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#24 /home/alumni/public_html/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('', Array)
#25 /home/alumni/public_html/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('', Array)
#26 /home/alumni/public_html/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#27 /home/alumni/public_html/yii(31): yii\base\Application->run()
#28 {main}
</pre>

<pre>
 composer show -i
bower-asset/bootstrap        v3.3.4             The most popular front-end framework for developing r...
bower-asset/jquery           2.1.4              
bower-asset/jquery.inputmask 3.1.63             jquery.inputmask is a jquery plugin which create an i...
bower-asset/punycode         v1.3.2             
bower-asset/typeahead.js     v0.10.5            
bower-asset/yii2-pjax        v2.0.4             
cebe/markdown                1.1.0              A super fast, highly extensible markdown parser for PHP
dmstr/yii2-bootstrap         0.1.1              yii2 bootstrap components and extensions from diemeis...
ezyang/htmlpurifier          v4.6.0             Standards compliant HTML filter written in PHP
fzaninotto/faker             v1.4.0             Faker is a PHP library that generates fake data for you.
phpspec/php-diff             v1.0.2             A comprehensive library for generating differences be...
schmunk42/yii2-giiant        dev-master 910c50c Gii CRUD generator for Yii 2 Framework
swiftmailer/swiftmailer      v5.4.0             Swiftmailer, free feature-rich PHP mailer
yiisoft/yii2                 2.0.4              Yii PHP Framework Version 2
yiisoft/yii2-bootstrap       2.0.4              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-codeception     2.0.4              The Codeception integration for the Yii framework
yiisoft/yii2-composer        2.0.3              The composer plugin for Yii extension installer
yiisoft/yii2-debug           2.0.4              The debugger extension for the Yii framework
yiisoft/yii2-faker           2.0.3              Fixture generator. The Faker integration for the Yii ...
yiisoft/yii2-gii             2.0.4              The Gii extension for the Yii framework
yiisoft/yii2-swiftmailer     2.0.4              The SwiftMailer integration for the Yii framework

</pre>

**Comment by alexweb** [comment]
How to fix this error?
