### ISSUE TITLE
fix Generator.php

### ISSUE THREAD

**Issue by akaNightmare** [schmunk42/yii2-giiant#58]
line 123 change to
```php
'relations'   => isset($relations[$tableName]) ? $relations[$tableName] : [],
```

**Comment by rhertogh** [comment]
Had the same problem (relations were not generated), this fixes the problem.

**Comment by schmunk42** [comment]
Thanks. Didn't get it in the first place.
Fixed in https://github.com/schmunk42/yii2-giiant/commit/d5a07d295809c058a763852c261da097784ce232
