### ISSUE TITLE
table prefix in model generator

### ISSUE THREAD

**Issue by bowl4fun** [schmunk42/yii2-giiant#8]
after install via composer and setup everything looks fine so far.
need to use table prefix in my db (provider), 
just didn't find any config docs in giiant and generating with "tbl_*" gives me 
models with  "TblTableName"  where "TableName" is suggested

**Comment by snelweg** [comment]
Using YII 2.03 table prefix is gone now?

![naamloos](https://cloud.githubusercontent.com/assets/1257901/6504084/99796a6e-c333-11e4-8bcf-c86f93a67e03.png)

**Comment by schmunk42** [comment]
There's a checkbox ... `use table prefix`.

I am not 100% sure, but I think Yii is always using the connection prefix from the database.

While giiant allows you to specify a table prefix, just for CRUD generation.
In giiant this setting is used to generate model class names like so: `prefix_model_name` => `app\models\ModelName`.

I'll clarify this and update the docs.

**Comment by snelweg** [comment]
@schmunk42 thank you for your answer.

I am in the process of migrating from Cake Php to YII. I want to know where to put the prefix, in what file.
I know there is a checkbox, just want to know how to supply the actual prefix.

**Comment by schmunk42** [comment]
Do you need a prefix for your database connection?
http://www.yiiframework.com/doc-2.0/yii-db-connection.html#$tablePrefix-detail
This applies to all tables from this connection.

You put that setting in the application config `config/main.php` components > db

**Comment by snelweg** [comment]
wow, that is great documentation!
And the prefix is indeed for the connection, all the table names have the same prefix, I want to use GII and this will make my life easier. 
Thanks and keep up the good work!

**Comment by Choockas** [comment]
in db.php :   <?php

return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=localhost;dbname= *******',
    'username' => '******',
    'password' => '********',
    'charset' => 'utf8',
	'tablePrefix' => 'forenc_'
];
Then generate CRUD.
After that  generate Model with option  Use Table Prefix (Check)
Voila tout.
PS
In models you can see  like  
public static function tableName()
    {
        return '{{%tablename_witout_prefix}}';
    }

**Comment by ik-j** [comment]
I used Giiant for CRUD generation, it didnt create any model :( I get error like: Class 'app\modules\crud\models\Faq' not found

**Comment by Quexer69** [comment]
Did you use the Web UI or the CLI batch command?

Does the table in the used db connection exists?!

Could you give some more information about your configuration?

**Comment by ik-j** [comment]
I used the CLI command. I updated console->config->main.php with  'controllerMap' as under:


```
return [
    'id' => 'app-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'console\controllers',
    'controllerMap' => [
    'batch' => [
        'class' => 'schmunk42\giiant\commands\BatchController',
        'overwrite' => true,
        'modelNamespace' => 'backend\\crud\\models',
        'crudTidyOutput' => true,
    ]
    ],
    'components' => [
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],  
        ],
    ],
    'params' => $params,
];

```

**Comment by schmunk42** [comment]
Double check your namespaces.

    app/modules/crud

and

    backend/crud

do not match.

Von meinem iPhone gesendet

**Comment by ik-j** [comment]
Where shud I check ? 

Schmunk I love your module giiant-yii2. I have been using it in all of my projects. Great piece :)

**Comment by schmunk42** [comment]
Thank you :bow:

Sorry I mixed up the namespace paths...

Could you try setting the `modelQueryNamespace` property like described here: https://github.com/schmunk42/yii2-giiant/blob/master/docs/20-batches.md

**Comment by Quexer69** [comment]
or look at the example and way we do it here:

'https://github.com/phundament/app/blob/master/src/config/giiant.php'

with application config

'https://github.com/phundament/app/blob/master/src/config/main.php'

**Comment by ik-j** [comment]
I am using Yii2 advanced app. So "CLI configuration" in advanced app would mean console->config->main.php ?

**Comment by Quexer69** [comment]
exactly ;-)

just merge your giiant.php configuration file into your console->config->main.php.

cheers chris
