### ISSUE TITLE
Giiant Model Class name always equals only to table name

### ISSUE THREAD

**Issue by cloudswitch** [schmunk42/yii2-giiant#88]
Hi, I've noticed a strange behaviour with Model Class field when trying to generate Giiant Model. It's required to type something into Model Class field, but it doesn't matter what you type. The name will be equal to table name anyway. I don't know if it was meant to be to behave like this, but I don't think so. Thx!

**Comment by cloudswitch** [comment]
As I see, it's by default already so in Yii2, so not only by Giiant, but by Gii also.

**Comment by schmunk42** [comment]
So can this be closed?

I strongly recommend the CLI tools like the batch command or directly with the gii generator, btw.
