### ISSUE TITLE
Giiant CRUD > Unknown Property – yii\base\UnknownPropertyException Getting, unknown property: common\models\User::isAdmin

### ISSUE THREAD

**Issue by cloudswitch** [schmunk42/yii2-giiant#89]
Hi,

after generating code with Giiant CRUD, I get this error message when trying to reach controller: Unknown Property – yii\base\UnknownPropertyException Getting, unknown property: common\models\User::isAdmin

When I comment this out:
'matchCallback' => function() use ($permission) {
                            return \Yii::$app->user->can($permission) || (\Yii::$app->user->identity && \Yii::$app->user->identity->isAdmin);
                        },

it seems to work. What is the problem here? Thx!

**Comment by schmunk42** [comment]
The controllers depend on yii2-user at the moment. https://github.com/dektrium/yii2-rbac

Looks like we need a better more customizable solution for this.
Eg. with auth item templates like in gtc (Yii1).

**Comment by cloudswitch** [comment]
no problem, I'm installing yii2-user also then. I just simply didn't know I need to install it also. Thanks a lot!

**Comment by schmunk42** [comment]
Thanks for pointing this out.

**Comment by cloudswitch** [comment]
I've installed yii2-user, but it doesn't work jet so I can't check if giiant works or not.

**Comment by schmunk42** [comment]
Uncomment the line in the template als a workaround.

Von meinem iPhone gesendet

**Comment by schmunk42** [comment]
Would this work better?

https://github.com/phundament/app/blob/feature/sprint-rc1/src/views/layouts/main.php#L53

**Comment by cloudswitch** [comment]
I have no clue, I'm not a professional, I don't understand what you mean, sorry.

**Comment by thadudexx** [comment]
how about replacing:
'matchCallback' => function($rule, $action) {
return
\Yii::$app->user->can(strtr($this->module->id, ['/' => '_', '-' => '_'])) ||
\Yii::$app->user->can(strtr($this->module->id . '/' . $this->id, ['/' => '_', '-' => '_'])) ||
\Yii::$app->user->can(strtr($this->module->id . '/' . $this->id . '/' . $action->id, ['/' => '_', '-' => '_'])) ||
(\Yii::$app->user->identity && \Yii::$app->user->identity->isAdmin);
},

with:
'roles'     => ['@']

wouldnt that be the easiest solution? At least if identityClass equals app\models\User.

**Comment by schmunk42** [comment]
@deacix We need to review this, I also ran into problems with the auth items after the latest merges?!

**Comment by schmunk42** [comment]
This should be fixed since a while.
