### ISSUE TITLE
route user/view in views/index.php not working

### ISSUE THREAD

**Issue by cloudswitch** [schmunk42/yii2-giiant#92]
Hi,

in views/index.php:

if ($rel = $model->getUser()->one()) {
                                            return yii\helpers\Html::a($rel->id, ["user/view", 'id' => $rel->id,], ["data-pjax" => 0]);

route user/view is not working (yii2-user installed). What else do I have to adjust to make it work? Thanks!

**Comment by schmunk42** [comment]
You need to use a custom provider to create the link, if your `User` model is outside the generated CRUDs.
