### ISSUE TITLE
DateProvider getting $attribute as string, but seems object requrired

### ISSUE THREAD

**Issue by cornernote** [schmunk42/yii2-giiant#98]
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property of non-object'

in /app/vendor/schmunk42/yii2-giiant/crud/providers/DateProvider.php:10

the reason is it's looking for `$attribute->name` but `$attribute` is a string containing `id`

**Comment by deacix** [comment]
Thank you fot the issue! Fixed!
